<?php
require __DIR__.'/app/bootstrap.php';
require __DIR__.'/app/views.php';
$admin=require_admin();$notice=null;$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  cc_rate_limit('admin-write:'.(int)$admin['id'],20,3600);verify_csrf($_POST['csrf']??null);$action=(string)($_POST['action']??'');
  if($action==='adjust_balance'){
   $identity=trim((string)($_POST['identity']??''));$raw=trim(str_replace(',','.',(string)($_POST['amount']??'0')));if(!preg_match('/^-?\d+(?:\.\d{1,2})?$/',$raw))throw new RuntimeException('Некорректная сумма.');$amount=(int)round((float)$raw*100);if($identity===''||$amount===0)throw new RuntimeException('Укажите пользователя и ненулевую сумму.');if(abs($amount)>100000000)throw new RuntimeException('Слишком большая корректировка.');
   $pdo=db();$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT id,username,balance_kopecks FROM users WHERE username=? OR email=? LIMIT 1 FOR UPDATE');$q->execute([$identity,mb_strtolower($identity)]);$u=$q->fetch();if(!$u)throw new RuntimeException('Пользователь не найден.');$before=(int)$u['balance_kopecks'];$after=max(0,$before+$amount);$actual=$after-$before;if($actual===0)throw new RuntimeException('Баланс не изменился.');$pdo->prepare('UPDATE users SET balance_kopecks=? WHERE id=?')->execute([$after,(int)$u['id']]);wallet_entry($pdo,(int)$u['id'],'admin_adjustment',$actual,$after,'admin:'.$admin['id'].':'.time(),['admin'=>$admin['username'],'requested'=>$amount]);$pdo->commit();$notice='Баланс '.$u['username'].' изменён на '.money_rub($actual).'.';}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
  }
 }catch(RuntimeException $e){$error=$e->getMessage();}catch(Throwable $e){error_log($e->__toString());$error='Не удалось выполнить административную операцию.';}
}
$stats=[];$stats['users']=(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn();$stats['rounds']=(int)db()->query('SELECT COUNT(*) FROM game_rounds')->fetchColumn();$stats['wagered']=(int)db()->query('SELECT COALESCE(SUM(cost_kopecks),0) FROM game_rounds')->fetchColumn();$stats['wins']=(int)db()->query('SELECT COALESCE(SUM(win_kopecks),0) FROM game_rounds')->fetchColumn();$stats['today']=(int)db()->query('SELECT COUNT(*) FROM game_rounds WHERE created_at>=CURDATE()')->fetchColumn();$stats['negative']=(int)db()->query('SELECT COUNT(*) FROM users WHERE balance_kopecks<0')->fetchColumn();$stats['active_mines']=(int)db()->query("SELECT COUNT(*) FROM user_game_states WHERE game_key='mini-mines' AND multiplier_map_json IS NOT NULL AND JSON_EXTRACT(multiplier_map_json,'$.round') IS NOT NULL")->fetchColumn();
$gameStats=db()->query("SELECT game_key,COUNT(*) rounds,COALESCE(SUM(cost_kopecks),0) cost,COALESCE(SUM(win_kopecks),0) wins,COALESCE(MAX(CASE WHEN bet_kopecks>0 THEN win_kopecks/bet_kopecks ELSE 0 END),0) best_mult FROM game_rounds GROUP BY game_key ORDER BY rounds DESC")->fetchAll();
$search=trim((string)($_GET['q']??''));if($search!==''){$q=db()->prepare('SELECT id,username,email,balance_kopecks,created_at,last_login_at FROM users WHERE username LIKE ? OR email LIKE ? ORDER BY id DESC LIMIT 30');$like='%'.$search.'%';$q->execute([$like,$like]);$users=$q->fetchAll();}else{$users=db()->query('SELECT id,username,email,balance_kopecks,created_at,last_login_at FROM users ORDER BY id DESC LIMIT 20')->fetchAll();}
$rounds=db()->query('SELECT r.id,r.game_key,r.mode,r.bet_kopecks,r.cost_kopecks,r.win_kopecks,r.created_at,u.username FROM game_rounds r JOIN users u ON u.id=r.user_id ORDER BY r.id DESC LIMIT 40')->fetchAll();
site_head('Админ-панель — CandyClub');echo '<body class="cc-site">';site_nav($admin);
?>
<main class="cc-container cc-account"><div class="cc-section-head"><div><h1 style="margin:0">Админ-панель</h1><p>Контроль виртуальной экономики, игровых раундов и технических аномалий.</p></div></div><?php if($notice): ?><div class="cc-form-success"><?=e($notice)?></div><?php endif; ?><?php if($error): ?><div class="cc-form-error"><?=e($error)?></div><?php endif; ?>
<div class="cc-admin-grid"><div class="cc-admin-stat"><span>Пользователи</span><strong><?=$stats['users']?></strong></div><div class="cc-admin-stat"><span>Раунды всего / сегодня</span><strong><?=$stats['rounds']?> / <?=$stats['today']?></strong></div><div class="cc-admin-stat"><span>Виртуально поставлено</span><strong><?=e(money_rub($stats['wagered']))?></strong></div><div class="cc-admin-stat"><span>Виртуально выиграно</span><strong><?=e(money_rub($stats['wins']))?></strong></div></div>
<div class="cc-integrity"><div class="<?=$stats['negative']?'bad':'good'?>"><span>Отрицательные балансы</span><strong><?=$stats['negative']?></strong></div><div class="good"><span>Активные Mines-сессии</span><strong><?=$stats['active_mines']?></strong></div><div><span>Наблюдаемый return</span><strong><?=$stats['wagered']>0?number_format($stats['wins']/$stats['wagered']*100,2).'%':'—'?></strong></div><div><span>CI / health</span><strong><a href="health.php">health.php</a></strong></div></div>
<section class="cc-history" style="margin-bottom:16px"><div class="cc-section-head"><div><h2>Аналитика по играм</h2><p>Наблюдаемая статистика фактических раундов. Это не сертифицированный RTP.</p></div></div><div style="overflow:auto"><table class="cc-table"><thead><tr><th>Игра</th><th>Раунды</th><th>Стоимость</th><th>Выигрыши</th><th>Return</th><th>Макс. ×</th></tr></thead><tbody><?php foreach($gameStats as $g): ?><tr><td><?=e($g['game_key'])?></td><td><?=number_format((int)$g['rounds'],0,',',' ')?></td><td><?=e(money_rub((int)$g['cost']))?></td><td><?=e(money_rub((int)$g['wins']))?></td><td><?=$g['cost']>0?number_format((int)$g['wins']/(int)$g['cost']*100,2).'%':'—'?></td><td><?=number_format((float)$g['best_mult'],2)?>×</td></tr><?php endforeach; ?></tbody></table></div></section>
<div class="cc-admin-two"><section class="cc-history"><h2>Корректировка виртуального баланса</h2><p style="color:var(--cc-muted)">Каждое изменение журналируется. Отрицательный итоговый баланс не допускается.</p><form method="post" class="cc-admin-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="adjust_balance"><input name="identity" maxlength="190" placeholder="Логин или email" required><input name="amount" inputmode="decimal" placeholder="5000 или -500" required><button class="cc-btn cc-btn-primary" type="submit">Применить</button></form><h2 style="margin-top:28px">Пользователи</h2><form method="get" class="cc-admin-form"><input name="q" maxlength="100" placeholder="Поиск по логину/email" value="<?=e($search)?>"><button class="cc-btn" type="submit">Найти</button></form><div style="overflow:auto"><table class="cc-table"><thead><tr><th>Пользователь</th><th>Баланс</th><th>Регистрация</th><th>Последний вход</th></tr></thead><tbody><?php foreach($users as $u): ?><tr><td><strong><?=e($u['username'])?></strong><br><small style="color:var(--cc-muted)"><?=e($u['email'])?></small></td><td><?=e(money_rub((int)$u['balance_kopecks']))?></td><td><?=e(date('d.m H:i',strtotime($u['created_at'])))?></td><td><?=$u['last_login_at']?e(date('d.m H:i',strtotime($u['last_login_at']))):'—'?></td></tr><?php endforeach; ?></tbody></table></div></section><section class="cc-history"><h2>Последние игровые раунды</h2><div style="overflow:auto"><table class="cc-table"><thead><tr><th>ID / игра</th><th>Игрок</th><th>Стоимость</th><th>Выигрыш</th></tr></thead><tbody><?php foreach($rounds as $r): ?><tr><td>#<?=$r['id']?> <small style="color:var(--cc-muted)"><?=e($r['game_key'])?> / <?=e($r['mode'])?></small></td><td><?=e($r['username'])?></td><td><?=e(money_rub((int)$r['cost_kopecks']))?></td><td class="<?=$r['win_kopecks']>0?'cc-plus':''?>"><?=e(money_rub((int)$r['win_kopecks']))?></td></tr><?php endforeach; ?></tbody></table></div></section></div></main>
<?php site_footer(); ?>
