<?php
require __DIR__.'/app/bootstrap.php';
require __DIR__.'/app/views.php';
$admin=require_admin();$notice=null;$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  verify_csrf($_POST['csrf']??null);$action=(string)($_POST['action']??'');
  if($action==='adjust_balance'){
   $identity=trim((string)($_POST['identity']??''));$rub=(float)str_replace(',','.',(string)($_POST['amount']??'0'));$amount=(int)round($rub*100);
   if($identity===''||$amount===0)throw new RuntimeException('Укажите пользователя и ненулевую сумму.');if(abs($amount)>100000000)throw new RuntimeException('Слишком большая корректировка.');
   $pdo=db();$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT id,username,balance_kopecks FROM users WHERE username=? OR email=? LIMIT 1 FOR UPDATE');$q->execute([$identity,$identity]);$u=$q->fetch();if(!$u)throw new RuntimeException('Пользователь не найден.');$before=(int)$u['balance_kopecks'];$after=max(0,$before+$amount);$actual=$after-$before;$pdo->prepare('UPDATE users SET balance_kopecks=? WHERE id=?')->execute([$after,(int)$u['id']]);wallet_entry($pdo,(int)$u['id'],'admin_adjustment',$actual,$after,'admin:'.$admin['id'],['admin'=>$admin['username'],'requested'=>$amount]);$pdo->commit();$notice='Баланс '.e($u['username']).' изменён на '.money_rub($actual).'.';}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
  }
 }catch(Throwable $e){$error=$e->getMessage();}
}
$stats=[];$stats['users']=(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn();$stats['rounds']=(int)db()->query('SELECT COUNT(*) FROM game_rounds')->fetchColumn();$stats['wagered']=(int)db()->query('SELECT COALESCE(SUM(cost_kopecks),0) FROM game_rounds')->fetchColumn();$stats['wins']=(int)db()->query('SELECT COALESCE(SUM(win_kopecks),0) FROM game_rounds')->fetchColumn();
$users=db()->query('SELECT id,username,email,balance_kopecks,created_at,last_login_at FROM users ORDER BY id DESC LIMIT 20')->fetchAll();$rounds=db()->query('SELECT r.id,r.game_key,r.mode,r.bet_kopecks,r.cost_kopecks,r.win_kopecks,r.created_at,u.username FROM game_rounds r JOIN users u ON u.id=r.user_id ORDER BY r.id DESC LIMIT 30')->fetchAll();
site_head('Админ-панель — CandyClub');echo '<body class="cc-site">';site_nav($admin);
?>
<main class="cc-container cc-account"><div class="cc-section-head"><div><h1 style="margin:0">Админ-панель</h1><p>Управление только виртуальной экономикой и контроль игровых раундов.</p></div></div><?php if($notice): ?><div class="cc-form-error" style="border-color:rgba(80,220,130,.3);background:rgba(80,220,130,.1);color:#8ef0af"><?=$notice?></div><?php endif; ?><?php if($error): ?><div class="cc-form-error"><?=e($error)?></div><?php endif; ?><div class="cc-admin-grid"><div class="cc-admin-stat"><span>Пользователи</span><strong><?=$stats['users']?></strong></div><div class="cc-admin-stat"><span>Раунды</span><strong><?=$stats['rounds']?></strong></div><div class="cc-admin-stat"><span>Виртуально поставлено</span><strong><?=e(money_rub($stats['wagered']))?></strong></div><div class="cc-admin-stat"><span>Виртуально выиграно</span><strong><?=e(money_rub($stats['wins']))?></strong></div></div><div class="cc-admin-two"><section class="cc-history"><h2>Корректировка баланса</h2><p style="color:var(--cc-muted)">Положительная сумма начисляет, отрицательная списывает. Каждое изменение пишется в журнал операций.</p><form method="post" class="cc-admin-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="adjust_balance"><input name="identity" placeholder="Логин или email" required><input name="amount" inputmode="decimal" placeholder="Сумма ₽, например 5000 или -500" required><button class="cc-btn cc-btn-primary" type="submit">Применить</button></form><h2 style="margin-top:28px">Новые пользователи</h2><div style="overflow:auto"><table class="cc-table"><thead><tr><th>Пользователь</th><th>Баланс</th><th>Регистрация</th></tr></thead><tbody><?php foreach($users as $u): ?><tr><td><strong><?=e($u['username'])?></strong><br><small style="color:var(--cc-muted)"><?=e($u['email'])?></small></td><td><?=e(money_rub((int)$u['balance_kopecks']))?></td><td><?=e(date('d.m H:i',strtotime($u['created_at'])))?></td></tr><?php endforeach; ?></tbody></table></div></section><section class="cc-history"><h2>Последние игровые раунды</h2><div style="overflow:auto"><table class="cc-table"><thead><tr><th>ID / игра</th><th>Игрок</th><th>Ставка</th><th>Выигрыш</th></tr></thead><tbody><?php foreach($rounds as $r): ?><tr><td>#<?=$r['id']?> <small style="color:var(--cc-muted)"><?=e($r['game_key'])?> / <?=e($r['mode'])?></small></td><td><?=e($r['username'])?></td><td><?=e(money_rub((int)$r['cost_kopecks']))?></td><td class="<?=$r['win_kopecks']>0?'cc-plus':''?>"><?=e(money_rub((int)$r['win_kopecks']))?></td></tr><?php endforeach; ?></tbody></table></div></section></div></main>
<?php site_footer(); ?>
