(function(){
'use strict';
var B=window.ARCADE_BOOT||{};function q(s){return document.querySelector(s)}var board=q('#arcBoard'),overlay=q('#arcOverlay'),msg=q('#arcMessage'),frame=q('.arc-board-frame');
var bets=[10,20,50,100,200,500,1000];var motion={
 'fruit-fiesta':{pre:7,tick:90,col:135,land:55,anticipate:560,className:'slow-roll',scatter:3},
 'temple-ways':{pre:8,tick:94,col:145,land:62,anticipate:650,className:'slow-roll',scatter:3},
 'jungle-hold':{pre:7,tick:102,col:155,land:64,anticipate:520,className:'slow-roll',scatter:6,special:'coin'},
 'crystal-clusters':{pre:6,tick:65,col:82,land:35,anticipate:420,className:'fast-roll',scatter:4},
 'sun-scroll':{pre:8,tick:100,col:150,land:65,anticipate:720,className:'slow-roll',scatter:3},
 'neon-rush':{pre:6,tick:58,col:76,land:30,anticipate:430,className:'fast-roll',scatter:3},
 'sky-pantheon':{pre:8,tick:88,col:138,land:58,anticipate:700,className:'slow-roll',scatter:4},
 'velvet-curtains':{pre:8,tick:98,col:150,land:62,anticipate:720,className:'slow-roll',scatter:3},
 'mystery-vault':{pre:7,tick:86,col:122,land:48,anticipate:590,className:'slow-roll',scatter:3}
};
var profile=motion[B.game]||motion['fruit-fiesta'];var ui={betIndex:3,turbo:false,sound:true};try{var saved=JSON.parse(localStorage.getItem('arcadeUi.'+B.game)||'{}');for(var sk in saved)ui[sk]=saved[sk]}catch(e){}
var S={balance:Number(B.balance||0),free:Number(B.freeSpins||0),last:0,busy:false,auto:0,audio:null};var keys=Object.keys(B.symbols||{});
function rub(v){return new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:v%1?2:0}).format(v)}function delay(ms){return new Promise(function(r){setTimeout(r,ui.turbo?Math.max(32,ms*.3):ms)})}function bet(){return bets[ui.betIndex]}function save(){try{localStorage.setItem('arcadeUi.'+B.game,JSON.stringify(ui))}catch(e){}}
function update(){q('#walletValue').textContent=rub(S.balance);var bs=document.querySelectorAll('[data-balance]');for(var i=0;i<bs.length;i++)bs[i].textContent=rub(S.balance);q('#betValue').textContent=rub(bet());q('#freeValue').textContent=S.free;q('#lastWin').textContent=rub(S.last);q('#modeBadge').textContent=S.free>0?'ФРИСПИНЫ':'ОСНОВНАЯ';q('#modeBadge').classList.toggle('arc-free',S.free>0);q('#turboBtn').classList.toggle('active',ui.turbo);q('#soundBtn').classList.toggle('active',ui.sound);q('#soundBtn').textContent=ui.sound?'🔊 ЗВУК':'🔇 ЗВУК';q('#autoBtn').classList.toggle('active',S.auto>0);q('#autoBtn').textContent=S.auto>0?'СТОП • '+S.auto:'АВТО ×20';var buy=q('#buyBtn');if(buy){var x=Number(B.buyBonus||0);buy.disabled=S.busy||S.free>0||x<=0;var price=q('#buyPrice');if(price)price.textContent=rub(bet()*x)}save()}
function tone(kind){if(!ui.sound)return;try{if(!S.audio)S.audio=new(window.AudioContext||window.webkitAudioContext)();var now=S.audio.currentTime;var palettes={'fruit-fiesta':[210,330,520],'temple-ways':[145,260,410],'jungle-hold':[120,220,360],'crystal-clusters':[320,520,760],'sun-scroll':[170,290,460],'neon-rush':[260,620,920],'sky-pantheon':[190,410,780],'velvet-curtains':[180,330,660],'mystery-vault':[130,390,710]};var p=palettes[B.game]||[180,390,620];function hit(f,t,d,g,type){var o=S.audio.createOscillator(),a=S.audio.createGain();o.type=type||'triangle';o.frequency.value=f;a.gain.setValueAtTime(.001,now+t);a.gain.linearRampToValueAtTime(g||.035,now+t+.01);a.gain.exponentialRampToValueAtTime(.001,now+t+(d||.12));o.connect(a).connect(S.audio.destination);o.start(now+t);o.stop(now+t+(d||.12)+.03)}if(kind==='roll'){hit(p[0],0,.07,.018);hit(p[1],.05,.07,.015)}if(kind==='land')hit(p[1],0,.07,.024);if(kind==='win'){hit(p[1],0,.13,.035);hit(p[2],.09,.15,.04);hit(p[2]*1.22,.19,.18,.045)}if(kind==='bonus'){for(var i=0;i<5;i++)hit(p[1]+i*80,i*.075,.18,.04)}if(kind==='error'){hit(115,0,.18,.04,'sawtooth');hit(82,.12,.18,.03,'sawtooth')}if(kind==='reveal'){hit(p[2],0,.25,.045);hit(p[2]*1.3,.12,.28,.04)}}catch(e){}}
function labelFor(sym){return window.ArcadeSymbols?window.ArcadeSymbols.label(B.game,sym,B.symbols):(B.symbols[sym]?B.symbols[sym].name:sym)}
function cellMarkup(sym){var svg=window.ArcadeSymbols?window.ArcadeSymbols.render(B.game,sym):null;if(!svg&&window.ArcadeSymbols&&window.ArcadeSymbols.fallback)svg=window.ArcadeSymbols.fallback();if(!svg)svg='<svg class="arc-svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="34" fill="#7552d8"/><path d="M50 20L60 43L84 45L66 61L72 84L50 71L28 84L34 61L16 45L40 43Z" fill="#fff"/></svg>';return '<span class="sym" title="'+labelFor(sym)+'">'+svg+'</span>'}
function render(grid,opts){opts=opts||{};board.innerHTML='';for(var i=0;i<B.cols*B.rows;i++){var c=Math.floor(i/B.rows),r=i%B.rows,sym=grid[i]||keys[0],el=document.createElement('div');el.className='arc-cell';el.setAttribute('data-index',String(i));el.setAttribute('data-sym',sym);el.style.gridColumn=String(c+1);el.style.gridRow=String(r+1);el.innerHTML=cellMarkup(sym);if(opts.sticky&&opts.sticky.indexOf(i)>=0)el.classList.add('sticky');board.appendChild(el)}}
function randomSym(){return keys[Math.floor(Math.random()*keys.length)]}
async function anticipation(text){msg.textContent=text;frame.classList.add('anticipation');tone('bonus');await delay(profile.anticipate);frame.classList.remove('anticipation')}
async function reelRoll(target){if(!board.children.length)render(Array.from({length:B.cols*B.rows},randomSym));var cells=Array.prototype.slice.call(board.children);board.classList.add(profile.className);for(var z=0;z<cells.length;z++)cells[z].classList.add('roll');q('#statusLeft').textContent='ПРОКРУТ';msg.textContent=B.game==='neon-rush'?'СИНХРОНИЗАЦИЯ ИМПУЛЬСОВ…':'БАРАБАНЫ В ДВИЖЕНИИ…';for(var k=0;k<profile.pre;k++){for(var a=0;a<cells.length;a++)cells[a].innerHTML=cellMarkup(randomSym());tone('roll');await delay(profile.tick)}var specialCount=0,anticipated=false;for(var c=0;c<B.cols;c++){for(var kk=0;kk<2;kk++){for(var cc=c;cc<B.cols;cc++)for(var r=0;r<B.rows;r++){var ri=cc*B.rows+r;cells[ri].innerHTML=cellMarkup(randomSym())}await delay(profile.land)}for(var rr=0;rr<B.rows;rr++){var idx=c*B.rows+rr,s=target[idx];cells[idx].innerHTML=cellMarkup(s);cells[idx].classList.remove('roll');cells[idx].classList.add('land');cells[idx].setAttribute('data-sym',s);if(s==='scatter'||(profile.special&&s===profile.special))specialCount++}tone('land');if(!anticipated&&c<B.cols-1&&specialCount>=Math.max(2,profile.scatter-1)){anticipated=true;await anticipation(profile.special==='coin'?'ЕЩЁ МОНЕТА ДЛЯ БОНУСА?':'БОНУС СОВСЕМ РЯДОМ…')}await delay(profile.col)}render(target);board.classList.remove(profile.className);await delay(170)}
async function curtainReveal(d){if(!d.curtains||!d.curtains.length)return;var layer=document.createElement('div');layer.className='arc-curtain-layer';for(var i=0;i<d.curtains.length;i++){var col=d.curtains[i],panel=document.createElement('div');panel.className='arc-curtain-panel';panel.style.left=(col/B.cols*100)+'%';panel.style.width=(100/B.cols)+'%';panel.innerHTML='<span></span>';layer.appendChild(panel)}frame.appendChild(layer);msg.textContent='ШТОРКИ ЗАКРЫВАЮТСЯ…';tone('bonus');await delay(650);render(d.display_grid||d.initial_grid);layer.classList.add('open');msg.textContent='ЗАНАВЕС ОТКРЫВАЕТСЯ';tone('reveal');await delay(760);layer.remove()}
async function mysteryReveal(d){if(!d.mystery_positions||!d.mystery_positions.length)return;for(var i=0;i<d.mystery_positions.length;i++){var el=board.children[d.mystery_positions[i]];if(el)el.classList.add('mystery-pulse')}msg.textContent='ТАЙНЫЕ БЛОКИ СИНХРОНИЗИРУЮТСЯ…';tone('bonus');await delay(620);frame.classList.add('fx-mystery');render(d.display_grid||d.initial_grid);tone('reveal');await delay(520);frame.classList.remove('fx-mystery')}
function highlight(pos){pos=pos||[];for(var i=0;i<pos.length;i++)if(board.children[pos[i]])board.children[pos[i]].classList.add('win')}
function stepFx(step){if(step.fx==='temple-dust'){frame.classList.add('fx-temple');setTimeout(function(){frame.classList.remove('fx-temple')},600)}if(step.fx==='neon-surge'){frame.classList.add('fx-neon');setTimeout(function(){frame.classList.remove('fx-neon')},620)}if(step.fx==='sun-expand'){frame.classList.add('fx-sun');setTimeout(function(){frame.classList.remove('fx-sun')},950)}if(step.fx==='crystal-blast'){for(var i=0;i<(step.positions||[]).length;i++){var e=board.children[step.positions[i]];if(e)e.classList.add('fx-blast')}}if(step.fx==='sky-lightning'){frame.classList.add('fx-sky');setTimeout(function(){frame.classList.remove('fx-sky')},680);for(var j=0;j<(step.multiplier_positions||[]).length;j++){var oe=board.children[step.multiplier_positions[j]];if(oe)oe.classList.add('fx-orb')}}if(step.fx==='curtain-win')frame.classList.add('fx-velvet');if(step.fx==='mystery-reveal')frame.classList.add('fx-mystery')}
async function popWin(amount,label){var e=document.createElement('div');e.className='arc-win-pop';e.innerHTML=rub(amount)+'<small>'+(label||'ВЫИГРЫШ')+'</small>';overlay.innerHTML='';overlay.appendChild(e);tone('win');await delay(amount>=bet()*10?850:560);overlay.innerHTML=''}
async function bigWin(total){if(total<bet()*10)return;var tier=total>=bet()*50?'EPIC WIN':(total>=bet()*25?'MEGA WIN':'BIG WIN');var e=document.createElement('div');e.className='arc-bigwin';e.innerHTML='<strong>'+tier+'</strong><span>'+rub(total)+'</span><small>'+Number(total/bet()).toFixed(1)+'× СТАВКИ</small>';overlay.innerHTML='';overlay.appendChild(e);tone('bonus');await delay(total>=bet()*50?1900:1300);overlay.innerHTML=''}
function toast(text){var e=document.createElement('div');e.className='arc-toast';e.textContent=text;document.body.appendChild(e);setTimeout(function(){e.remove()},2300)}
async function animateFeature(feature){var box=q('#featureBox');box.innerHTML='';if(!feature||feature.type!=='hold')return;var wrap=document.createElement('div');wrap.className='arc-feature';wrap.innerHTML='<h3>'+(feature.title||'БОНУС')+'</h3><div class="arc-hold-grid" id="holdGrid"></div><div class="arc-respins" id="respins">РЕСПИНЫ: 3</div>';box.appendChild(wrap);var g=q('#holdGrid'),prev={};var frames=feature.frames||[];for(var fi=0;fi<frames.length;fi++){var f=frames[fi],coins=f.coins||{};g.innerHTML='';for(var i=0;i<15;i++){var ce=document.createElement('div');if(coins[i]!=null){ce.className='arc-coin'+(prev[i]==null?' new':'');ce.textContent=(coins[i]/100).toFixed(coins[i]%100?1:0)+'×'}else ce.className='arc-empty';g.appendChild(ce)}prev=coins;q('#respins').textContent='РЕСПИНЫ: '+f.respins;tone(f.new&&f.new.length?'win':'land');await delay(660)}if(feature.full)toast('🏆 ПОЛНОЕ ПОЛЕ!');await popWin(Number(feature.win||0),'БОНУС ЗОЛОТОГО ТОТЕМА')}
async function spin(mode){mode=mode||'normal';if(S.busy)return;var expectedCost=mode==='buy_bonus'?bet()*Number(B.buyBonus||0):bet();if(S.free<=0&&S.balance<expectedCost){msg.textContent='НЕДОСТАТОЧНО ВИРТУАЛЬНЫХ СРЕДСТВ';tone('error');S.auto=0;update();return}S.busy=true;q('#spinBtn').classList.add('busy');q('#betMinus').disabled=q('#betPlus').disabled=true;update();msg.textContent=mode==='buy_bonus'?'ПОКУПАЕМ БОНУС…':'СЕРВЕР РАССЧИТЫВАЕТ ВРАЩЕНИЕ…';q('#featureBox').innerHTML='';try{var res=await fetch('api/game/arcade-spin.php',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-Token':B.csrf},credentials:'same-origin',body:JSON.stringify({game:B.game,bet:bet(),mode:mode})});var d=await res.json().catch(function(){return{ok:false,error:'Некорректный ответ сервера.'}});if(!res.ok||!d.ok)throw new Error(d.error||'Ошибка игры.');S.balance=Number(d.balance_before)-Number(d.cost);S.last=0;if(d.is_free_spin)S.free=Math.max(0,S.free-1);update();q('#statusRight').textContent=d.badge||B.title;await reelRoll(d.initial_grid);await curtainReveal(d);await mysteryReveal(d);var totalSteps=0;var steps=d.steps||[];for(var si=0;si<steps.length;si++){var step=steps[si];highlight(step.positions||[]);var mp=step.multiplier_positions||[];for(var pi=0;pi<mp.length;pi++)if(board.children[mp[pi]])board.children[mp[pi]].classList.add('win');stepFx(step);if(step.multiplier_total)toast('⚡ СОБРАН МНОЖИТЕЛЬ ×'+(step.persistent_multiplier||step.multiplier_total));msg.textContent=(step.label||'ВЫИГРЫШ')+' • +'+rub(Number(step.win||0));q('#statusLeft').textContent=step.extra||step.label||'ВЫИГРЫШ';totalSteps+=Number(step.win||0);S.last=totalSteps;update();await delay(120);await popWin(Number(step.win||0),step.label);await delay(210);render(step.grid_after||d.display_grid||d.initial_grid,{sticky:d.sticky||[]});await delay(B.game==='crystal-clusters'?330:470)}await animateFeature(d.feature);if(Number(d.free_spins_awarded||0)>0){tone('bonus');toast('🎁 +'+d.free_spins_awarded+' ФРИСПИНОВ');await delay(760)}S.balance=Number(d.balance_after);S.last=Number(d.total_win||0);S.free=Number(d.free_spins||0);var finalGrid=steps.length?steps[steps.length-1].grid_after:(d.display_grid||d.initial_grid);render(finalGrid,{sticky:d.sticky||[]});q('#statusLeft').textContent='ГОТОВО';q('#statusRight').textContent=d.badge||B.title;msg.textContent=S.last>0?'ИТОГ ВРАЩЕНИЯ '+rub(S.last):(S.free>0?'СЛЕДУЮЩИЙ ФРИСПИН':'ЕЩЁ РАЗ!');update();await bigWin(S.last);S.busy=false;q('#spinBtn').classList.remove('busy');q('#betMinus').disabled=q('#betPlus').disabled=false;update();if(S.free>0){await delay(1050);if(!S.busy)spin('normal');return}if(S.auto>0&&mode==='normal'){S.auto--;update();if(S.auto>0){await delay(930);spin('normal')}}}catch(e){S.busy=false;q('#spinBtn').classList.remove('busy');q('#betMinus').disabled=q('#betPlus').disabled=false;S.auto=0;update();tone('error');msg.textContent=e.message||'ОШИБКА СЕРВЕРА'}}
q('#betMinus').onclick=function(){if(!S.busy&&S.free<=0){ui.betIndex=Math.max(0,ui.betIndex-1);update()}};q('#betPlus').onclick=function(){if(!S.busy&&S.free<=0){ui.betIndex=Math.min(bets.length-1,ui.betIndex+1);update()}};q('#spinBtn').onclick=function(){spin('normal')};q('#autoBtn').onclick=function(){if(S.auto){S.auto=0;update();return}S.auto=20;update();spin('normal')};q('#turboBtn').onclick=function(){ui.turbo=!ui.turbo;update()};q('#soundBtn').onclick=function(){ui.sound=!ui.sound;update();if(ui.sound)tone('land')};var buy=q('#buyBtn');if(buy)buy.onclick=function(){if(S.busy||S.free>0)return;var cost=bet()*Number(B.buyBonus||0);if(confirm('Купить бонус за '+rub(cost)+' виртуального баланса?'))spin('buy_bonus')};document.addEventListener('keydown',function(e){if(e.code==='Space'&&!e.repeat){e.preventDefault();spin('normal')}});render(Array.from({length:B.cols*B.rows},randomSym));update();
})();
