(() => {
  'use strict';
  const B=window.ARCADE_BOOT, $=s=>document.querySelector(s), board=$('#arcBoard'), overlay=$('#arcOverlay'), msg=$('#arcMessage');
  const bets=[10,20,50,100,200,500,1000];let ui={betIndex:3,turbo:false,sound:true};try{ui={...ui,...(JSON.parse(localStorage.getItem('arcadeUi.'+B.game)||'{}')||{})};}catch{}
  const S={balance:Number(B.balance||0),free:Number(B.freeSpins||0),last:0,busy:false,auto:0,audio:null};
  const keys=Object.keys(B.symbols), rub=v=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:v%1?2:0}).format(v), delay=ms=>new Promise(r=>setTimeout(r,ui.turbo?Math.max(35,ms*.32):ms));
  const bet=()=>bets[ui.betIndex];
  const save=()=>localStorage.setItem('arcadeUi.'+B.game,JSON.stringify(ui));
  function update(){
    $('#walletValue').textContent=rub(S.balance);document.querySelectorAll('[data-balance]').forEach(e=>e.textContent=rub(S.balance));$('#betValue').textContent=rub(bet());$('#freeValue').textContent=S.free;$('#lastWin').textContent=rub(S.last);$('#modeBadge').textContent=S.free>0?'ФРИСПИНЫ':'ОСНОВНАЯ';$('#modeBadge').classList.toggle('arc-free',S.free>0);$('#turboBtn').classList.toggle('active',ui.turbo);$('#soundBtn').classList.toggle('active',ui.sound);$('#soundBtn').textContent=ui.sound?'🔊 ЗВУК':'🔇 ЗВУК';$('#autoBtn').classList.toggle('active',S.auto>0);$('#autoBtn').textContent=S.auto>0?'СТОП • '+S.auto:'АВТО ×20';save();
  }
  function tone(kind){if(!ui.sound)return;try{S.audio||=new(window.AudioContext||window.webkitAudioContext)();const now=S.audio.currentTime;const hit=(f,t,d=.12,g=.035)=>{const o=S.audio.createOscillator(),a=S.audio.createGain();o.type='triangle';o.frequency.value=f;a.gain.setValueAtTime(.001,now+t);a.gain.linearRampToValueAtTime(g,now+t+.01);a.gain.exponentialRampToValueAtTime(.001,now+t+d);o.connect(a).connect(S.audio.destination);o.start(now+t);o.stop(now+t+d+.03);};if(kind==='roll'){hit(180,0,.08,.02);hit(240,.06,.08,.018)}if(kind==='land')hit(390,0,.07,.025);if(kind==='win'){hit(520,0);hit(680,.09);hit(840,.18,.16,.04)}if(kind==='bonus')[0,1,2,3,4].forEach(i=>hit(430+i*105,i*.08,.19,.04));if(kind==='error'){hit(120,0,.18,.04);hit(90,.12,.18,.03)}}catch{}}
  function cellMarkup(sym){const d=B.symbols[sym]||{icon:'?',name:sym};return `<span class="sym" title="${d.name}">${d.icon}</span>`;}
  function render(grid,opts={}){board.innerHTML='';for(let i=0;i<B.cols*B.rows;i++){const c=Math.floor(i/B.rows),r=i%B.rows,sym=grid[i]||keys[0],el=document.createElement('div');el.className='arc-cell';el.dataset.index=i;el.dataset.sym=sym;el.style.gridColumn=String(c+1);el.style.gridRow=String(r+1);el.innerHTML=cellMarkup(sym);if(opts.sticky?.includes(i))el.classList.add('sticky');board.append(el);}}
  function randomSym(){return keys[Math.floor(Math.random()*keys.length)];}
  async function reelRoll(target){if(!board.children.length)render(Array.from({length:B.cols*B.rows},randomSym));const cells=[...board.children];cells.forEach(e=>e.classList.add('roll'));$('#statusLeft').textContent='ПРОКРУТ';msg.textContent='БАРАБАНЫ В ДВИЖЕНИИ…';for(let k=0;k<7;k++){for(const e of cells)e.innerHTML=cellMarkup(randomSym());tone('roll');await delay(80);}for(let c=0;c<B.cols;c++){for(let k=0;k<2;k++){for(let cc=c;cc<B.cols;cc++)for(let r=0;r<B.rows;r++){const i=cc*B.rows+r;cells[i].innerHTML=cellMarkup(randomSym());}await delay(45);}for(let r=0;r<B.rows;r++){const i=c*B.rows+r;cells[i].innerHTML=cellMarkup(target[i]);cells[i].classList.remove('roll');cells[i].classList.add('land');cells[i].dataset.sym=target[i];}tone('land');await delay(115);}render(target);await delay(180);}
  function highlight(pos=[]){for(const i of pos)board.children[i]?.classList.add('win');}
  async function popWin(amount,label){const e=document.createElement('div');e.className='arc-win-pop';e.innerHTML=`${rub(amount)}<small>${label||'ВЫИГРЫШ'}</small>`;overlay.replaceChildren(e);tone('win');await delay(amount>=bet()*10?800:520);overlay.innerHTML='';}
  function toast(text){const e=document.createElement('div');e.className='arc-toast';e.textContent=text;document.body.append(e);setTimeout(()=>e.remove(),2100);}
  async function animateFeature(feature){const box=$('#featureBox');box.innerHTML='';if(!feature||feature.type!=='hold')return;const wrap=document.createElement('div');wrap.className='arc-feature';wrap.innerHTML=`<h3>${feature.title||'БОНУС'}</h3><div class="arc-hold-grid" id="holdGrid"></div><div class="arc-respins" id="respins">РЕСПИНЫ: 3</div>`;box.append(wrap);const g=$('#holdGrid');let prev=new Set();for(const frame of feature.frames||[]){g.innerHTML='';const coins=frame.coins||{};for(let i=0;i<15;i++){if(coins[i]!=null){const e=document.createElement('div');e.className='arc-coin'+(!prev.has(String(i))?' new':'');e.textContent=(coins[i]/100).toFixed(coins[i]%100?1:0)+'×';g.append(e);}else{const e=document.createElement('div');e.className='arc-empty';g.append(e);}}prev=new Set(Object.keys(coins));$('#respins').textContent='РЕСПИНЫ: '+frame.respins;tone(frame.new?.length?'win':'land');await delay(620);}if(feature.full)toast('🏆 ПОЛНОЕ ПОЛЕ! +50× ставки');await popWin(Number(feature.win||0),'БОНУС ЗОЛОТОГО ТОТЕМА');}
  async function spin(){
    if(S.busy)return;if(S.free<=0&&S.balance<bet()){msg.textContent='НЕДОСТАТОЧНО ВИРТУАЛЬНЫХ СРЕДСТВ';tone('error');S.auto=0;update();return;}S.busy=true;$('#spinBtn').classList.add('busy');$('#betMinus').disabled=$('#betPlus').disabled=true;msg.textContent='СЕРВЕР РАССЧИТЫВАЕТ ВРАЩЕНИЕ…';$('#featureBox').innerHTML='';
    try{const res=await fetch('api/game/arcade-spin.php',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-Token':B.csrf},credentials:'same-origin',body:JSON.stringify({game:B.game,bet:bet()})});const d=await res.json().catch(()=>({ok:false,error:'Некорректный ответ сервера.'}));if(!res.ok||!d.ok)throw new Error(d.error||'Ошибка игры.');
      S.balance=Number(d.balance_before)-Number(d.cost);S.last=0;if(d.is_free_spin)S.free=Math.max(0,S.free-1);update();$('#statusRight').textContent=d.badge||B.title;await reelRoll(d.initial_grid);let totalSteps=0;
      for(const step of d.steps||[]){highlight(step.positions||[]);msg.textContent=(step.label||'ВЫИГРЫШ')+' • +'+rub(Number(step.win||0));$('#statusLeft').textContent=step.extra||step.label||'ВЫИГРЫШ';totalSteps+=Number(step.win||0);S.last=totalSteps;update();await popWin(Number(step.win||0),step.label);await delay(180);render(step.grid_after||d.initial_grid,{sticky:d.sticky||[]});await delay(420);}
      await animateFeature(d.feature);if(Number(d.free_spins_awarded||0)>0){tone('bonus');toast('🎁 +'+d.free_spins_awarded+' ФРИСПИНОВ');await delay(700);}S.balance=Number(d.balance_after);S.last=Number(d.total_win||0);S.free=Number(d.free_spins||0);render((d.steps?.length?d.steps[d.steps.length-1].grid_after:d.initial_grid),{sticky:d.sticky||[]});$('#statusLeft').textContent='ГОТОВО';$('#statusRight').textContent=d.badge||B.title;msg.textContent=S.last>0?'ИТОГ ВРАЩЕНИЯ '+rub(S.last):(S.free>0?'СЛЕДУЮЩИЙ ФРИСПИН':'ЕЩЁ РАЗ!');update();
      S.busy=false;$('#spinBtn').classList.remove('busy');$('#betMinus').disabled=$('#betPlus').disabled=false;
      if(S.free>0){await delay(950);if(!S.busy)spin();return;}if(S.auto>0){S.auto--;update();if(S.auto>0){await delay(850);spin();}}
    }catch(e){S.busy=false;$('#spinBtn').classList.remove('busy');$('#betMinus').disabled=$('#betPlus').disabled=false;S.auto=0;update();tone('error');msg.textContent=e.message||'ОШИБКА СЕРВЕРА';}
  }
  $('#betMinus').onclick=()=>{if(!S.busy){ui.betIndex=Math.max(0,ui.betIndex-1);update();}};$('#betPlus').onclick=()=>{if(!S.busy){ui.betIndex=Math.min(bets.length-1,ui.betIndex+1);update();}};$('#spinBtn').onclick=spin;$('#autoBtn').onclick=()=>{if(S.auto){S.auto=0;update();return;}S.auto=20;update();spin();};$('#turboBtn').onclick=()=>{ui.turbo=!ui.turbo;update();};$('#soundBtn').onclick=()=>{ui.sound=!ui.sound;update();if(ui.sound)tone('land');};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat){e.preventDefault();spin();}});
  render(Array.from({length:B.cols*B.rows},randomSym));update();
})();
