<?php
require __DIR__.'/app/bootstrap.php';
require __DIR__.'/app/views.php';
require __DIR__.'/app/game_catalog.php';
$user=require_login();$uid=(int)$user['id'];$progress=player_progress($uid);$division=cc_division($progress['level']);$missions=cc_daily_missions($uid);$achievements=cc_achievements($uid);$leaderboard=cc_weekly_leaderboard(15);$controls=cc_controls($uid);$recent=cc_recent_games($uid,6);$catalog=game_catalog();
function club_game_meta(string $key,array $catalog): array {
    if(str_starts_with($key,'mini-')){$m=substr($key,5);$defs=['plinko'=>['Плинко Лаб','●','mini.php?game=plinko'],'mines'=>['Кристальные мины','◆','mini.php?game=mines'],'wheel'=>['Колесо импульса','◉','mini.php?game=wheel'],'crash'=>['Ракетный импульс','▲','mini.php?game=crash']];return $defs[$m]??[$key,'•','index.php#mini'];}
    if(isset($catalog[$key]))return[$catalog[$key]['title'],$catalog[$key]['icon'],$key==='sweet-cascade'?'game.php':$catalog[$key]['route']];return[$key,'•','index.php#slots'];
}
site_head('Клуб игрока — CandyClub');echo '<body class="cc-site">';site_nav($user);
?>
<main class="cc-container cc-club-page">
<section class="cc-club-hero"><div class="cc-club-rank"><div class="cc-rank-orb"><?=e($division['icon'])?></div><div><span>Дивизион</span><h1><?=e($division['name'])?></h1><p>Уровень <?=$progress['level']?> • <?=number_format($progress['xp'],0,',',' ')?> XP</p></div></div><div class="cc-club-progress"><div><span>Прогресс уровня</span><strong><?=round($progress['progress'])?>%</strong></div><div class="cc-xp"><i style="width:<?=round($progress['progress'],1)?>%"></i></div><small><?=$division['next']?'Следующий дивизион на уровне '.$division['next']:'Высший дивизион достигнут'?></small></div></section>

<section class="cc-section compact"><div class="cc-section-head"><div><h2>Ежедневные миссии</h2><p>Выполняются автоматически по серверной истории. Награды — только виртуальный баланс.</p></div></div><div class="cc-mission-grid" id="missionGrid"><?php foreach($missions as $m): ?><article class="cc-mission-card <?=$m['claimed']?'claimed':($m['complete']?'complete':'')?>"><div class="cc-mission-top"><div><strong><?=e($m['title'])?></strong><small><?=e($m['description'])?></small></div><b>+<?=e(money_rub((int)$m['reward']))?></b></div><div class="cc-progress"><i style="width:<?=round($m['progress'],1)?>%"></i></div><div class="cc-mission-foot"><span><?=e((string)$m['current'])?> / <?=e((string)$m['target'])?></span><button data-claim="<?=e($m['key'])?>" <?=$m['complete']&&!$m['claimed']?'':'disabled'?>><?=$m['claimed']?'ПОЛУЧЕНО':($m['complete']?'ЗАБРАТЬ':'В ПРОЦЕССЕ')?></button></div></article><?php endforeach; ?></div></section>

<section class="cc-club-two"><div class="cc-club-panel"><div class="cc-section-head"><div><h2>Достижения</h2><p>Постоянные цели без ручного включения.</p></div></div><div class="cc-achievement-grid"><?php foreach($achievements as $a): ?><article class="cc-achievement <?=$a['done']?'done':''?>"><i><?=e($a['icon'])?></i><div><strong><?=e($a['title'])?></strong><small><?=e($a['description'])?></small><span><?=e($a['progress'])?></span></div></article><?php endforeach; ?></div></div><div class="cc-club-panel"><div class="cc-section-head"><div><h2>Недельный лидерборд</h2><p>Рейтинг по лучшему множителю, а не по размеру ставки.</p></div></div><div class="cc-leaderboard"><?php if(!$leaderboard): ?><div class="cc-empty">На этой неделе пока нет выигрышных раундов.</div><?php else: foreach($leaderboard as $i=>$r): ?><div class="cc-leader-row"><b>#<?=$i+1?></b><span><?=e(cc_mask_name((string)$r['username']))?></span><small><?=number_format((float)$r['best_mult'],2)?>×</small><strong><?=e(money_rub((int)$r['best_win']))?></strong></div><?php endforeach; endif; ?></div></div></section>

<section class="cc-club-two"><div class="cc-club-panel"><div class="cc-section-head"><div><h2>Недавние игры</h2><p>Быстрый возврат туда, где вы остановились.</p></div></div><div class="cc-recent-grid"><?php if(!$recent): ?><div class="cc-empty">История появится после первого раунда.</div><?php else: foreach($recent as $r): [$title,$icon,$href]=club_game_meta((string)$r['game_key'],$catalog); ?><a href="<?=e($href)?>"><i><?=e($icon)?></i><div><strong><?=e($title)?></strong><small><?=$r['rounds']?> раундов • <?=e(date('d.m H:i',strtotime($r['last_played'])))?></small></div><span>→</span></a><?php endforeach; endif; ?></div></div>
<div class="cc-club-panel" id="playControls"><div class="cc-section-head"><div><h2>Контроль игры</h2><p>Ограничения применяются сервером, поэтому их нельзя обойти изменением JavaScript.</p></div></div><div class="cc-control-form"><label>Максимальная базовая ставка<select id="maxBetSelect"><option value="0">Без личного лимита</option><?php foreach([10,20,50,100,200,500,1000,2000] as $v): ?><option value="<?=$v?>" <?=$controls['max_bet_rub']===$v?'selected':''?>><?=$v?> ₽</option><?php endforeach; ?></select></label><label>Напоминание о длительности сессии<select id="reminderSelect"><option value="0" <?=$controls['session_reminder_minutes']===0?'selected':''?>>Выключено</option><?php foreach([15,30,60,120] as $v): ?><option value="<?=$v?>" <?=$controls['session_reminder_minutes']===$v?'selected':''?>>Каждые <?=$v?> мин.</option><?php endforeach; ?></select></label><label>Игровая пауза<select id="pauseSelect"><option value="0">Не менять</option><option value="1">1 час</option><option value="24">24 часа</option><option value="168">7 дней</option></select></label><button class="cc-btn cc-btn-primary" id="saveControls">Сохранить ограничения</button><?php if($controls['pause_until']>time()): ?><div class="cc-pause-active">Пауза активна до <strong><?=e(date('d.m.Y H:i',$controls['pause_until']))?></strong>. Раннее снятие через интерфейс недоступно.</div><?php endif; ?></div></div></section>
</main>
<script>window.CLUB_BOOT=<?=json_encode(['csrf'=>csrf_token(),'controls'=>$controls],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script><script src="<?=asset_url('club.js')?>"></script>
<?php site_footer(); ?>
