(() => {
  'use strict'; const S=window.SC;
  if(!Number.isFinite(S.state.stormCharge))S.state.stormCharge=0;
  S.stormActive=false; S.lastMultChanges=[];
  S.ensureJuiceUI=()=>{if(S.$('#stormMeter'))return;const meter=document.createElement('div');meter.id='stormMeter';meter.className='storm-meter';meter.innerHTML='<div class="storm-meter-fill" id="stormFill"></div><div class="storm-meter-label">СЛАДКИЙ ШТОРМ <b id="stormValue">0%</b></div>';S.$('.board-frame').insertAdjacentElement('beforebegin',meter);const combo=document.createElement('div');combo.id='comboPill';combo.className='combo-pill';S.$('.board-frame').append(combo);S.updateJuiceUI();};
  S.updateJuiceUI=()=>{const m=S.$('#stormMeter'),f=S.$('#stormFill'),v=S.$('#stormValue');if(!m||!f||!v)return;const n=Math.max(0,Math.min(100,Math.round(S.state.stormCharge||0)));f.style.width=`${n}%`;v.textContent=`${n}%`;m.classList.toggle('ready',n>=100);};
  S.toast=text=>{const e=document.createElement('div');e.className='feature-toast';e.textContent=text;document.body.append(e);setTimeout(()=>e.remove(),2300);};
  S.flash=()=>{const e=document.createElement('div');e.className='screen-flash';document.body.append(e);setTimeout(()=>e.remove(),650);};
  S.particlesFromCell=(index,count=10)=>{const cell=S.els.grid.children[index];if(!cell)return;const r=cell.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,cols=['#fff06b','#ff58c8','#62eaff','#8a5cff','#64eb79'];for(let i=0;i<count;i++){const p=document.createElement('i');p.className='juice-particle';p.style.left=`${cx}px`;p.style.top=`${cy}px`;p.style.color=cols[i%cols.length];p.style.background='currentColor';p.style.setProperty('--dx',`${-80+Math.random()*160}px`);p.style.setProperty('--dy',`${-100+Math.random()*150}px`);p.style.setProperty('--dur',`${.55+Math.random()*.55}s`);document.body.append(p);setTimeout(()=>p.remove(),1300);}};
  S.showCombo=(cascade,factor)=>{const e=S.$('#comboPill');if(!e)return;e.classList.remove('show');void e.offsetWidth;e.innerHTML=`КОМБО ×${factor.toFixed(2).replace('.00','')} <small>• каскад ${cascade}</small>`;e.classList.add('show');};
  S.comboFactor=cascade=>cascade<=1?1:cascade===2?1.2:cascade===3?1.45:cascade===4?1.75:cascade===5?2.1:Math.min(3,2.1+(cascade-5)*.2);
  S.addStormCharge=(total,cascades=0)=>{const ratio=total/Math.max(1,S.bet()),gain=total>0?Math.min(30,7+cascades*3+Math.sqrt(ratio)*2.2):3;S.state.stormCharge=Math.min(100,(S.state.stormCharge||0)+gain);S.updateJuiceUI();S.saveState();if(S.state.stormCharge>=100)S.toast('⚡ СЛАДКИЙ ШТОРМ ЗАРЯЖЕН — усилит следующее обычное вращение!');};
  S.seedMultipliers=(count=5,strong=false)=>{const available=[...Array(S.CELL_COUNT).keys()].sort(()=>Math.random()-.5).slice(0,count);S.lastMultChanges=[];for(const i of available){const from=S.multiplierMap[i]||0,to=strong?[3,5,10][Math.floor(Math.random()*3)]:[2,2,3,3,5][Math.floor(Math.random()*5)];S.multiplierMap[i]=Math.max(from,to);S.lastMultChanges.push({pos:i,from,to:S.multiplierMap[i]});}return available;};
  S.applyStormIfReady=async()=>{if((S.state.stormCharge||0)<100)return false;S.state.stormCharge=0;S.stormActive=true;S.seedMultipliers(6,true);S.updateJuiceUI();S.saveState();S.$('.board-frame')?.classList.add('powered');S.flash();S.sound('bonus');S.toast('⚡ СЛАДКИЙ ШТОРМ: 6 усиленных клеток-множителей!');await S.delay(520);return true;};
  S.finishStorm=()=>{S.stormActive=false;S.$('.board-frame')?.classList.remove('powered');};
  S.decorateMultiplierChanges=()=>{for(const ch of S.lastMultChanges||[]){const cell=S.els.grid.children[ch.pos];if(!cell)continue;cell.classList.add(ch.from?'mult-up':'mult-new');S.particlesFromCell(ch.pos,ch.from?14:9);}S.lastMultChanges=[];};
  S.candyBurst=async(cascade)=>{const n=cascade>=6?5:3,spots=S.seedMultipliers(n,cascade>=6);S.renderGrid();for(const i of spots){S.els.grid.children[i]?.classList.add('blast','mult-new');S.particlesFromCell(i,12);}S.flash();S.sound('bonus');S.toast(cascade>=6?'🌈 МЕГА-БУРСТ: поле усилено!':'🍭 СЛАДКИЙ ВЗРЫВ: новые множители!');await S.delay(580);};
  S.animateRoll=async target=>{if(!S.grid.length){S.grid=S.randomGrid();S.renderGrid();}const cells=[...S.els.grid.children],frame=S.$('.board-frame');S.els.grid.classList.add('spinning');cells.forEach(c=>c.classList.add('reel-roll'));S.els.cascade.textContent='ПРОКРУТ';S.setMessage('СИМВОЛЫ В ДВИЖЕНИИ…');
    const randomizeCols=(from=0)=>{for(let c=from;c<S.COLS;c++)for(let r=0;r<S.ROWS;r++){const i=r*S.COLS+c,art=cells[i]?.querySelector('.symbol-art');if(art)art.innerHTML=S.svgFor(S.weightedSymbol());}};
    for(let k=0;k<7;k++){randomizeCols(0);S.sound('drop');await S.delay(95);}let landedScatters=0,anticipated=false;
    for(let c=0;c<S.COLS;c++){for(let k=0;k<2;k++){randomizeCols(c);await S.delay(55);}for(let r=0;r<S.ROWS;r++){const i=r*S.COLS+c,cell=cells[i],type=target[i],art=cell?.querySelector('.symbol-art');if(!cell||!art)continue;art.innerHTML=S.svgFor(type);cell.classList.remove('reel-roll');cell.classList.add('column-land');if(type==='scatter'){cell.classList.add('scatter','scatter-anticipate');landedScatters++;}}S.sound('click');if(landedScatters>=2&&c<S.COLS-1&&!anticipated){anticipated=true;S.setMessage('ЕЩЁ ОДИН БОНУСНЫЙ СИМВОЛ?');frame?.classList.add('win-glow');await S.delay(650);frame?.classList.remove('win-glow');}await S.delay(115);}
    S.grid=target;S.renderGrid();S.els.grid.classList.remove('spinning');S.els.cascade.textContent='ПРОВЕРКА';await S.delay(230);
  };
  S.ensureJuiceUI();
})();
