(() => {
  'use strict'; const S=window.SC;
  S.neighbors=i=>{const r=Math.floor(i/S.COLS),c=i%S.COLS,out=[];if(r>0)out.push(i-S.COLS);if(r<S.ROWS-1)out.push(i+S.COLS);if(c>0)out.push(i-1);if(c<S.COLS-1)out.push(i+1);return out;};
  S.findClusters=()=>{const seen=new Set(),wins=[];for(let i=0;i<S.CELL_COUNT;i++){if(seen.has(i)||S.SYMBOLS[S.grid[i]].scatter)continue;const type=S.grid[i],stack=[i],cells=[];seen.add(i);while(stack.length){const cur=stack.pop();cells.push(cur);for(const n of S.neighbors(cur))if(!seen.has(n)&&S.grid[n]===type){seen.add(n);stack.push(n);}}if(cells.length>=5)wins.push({type,cells});}return wins;};
  S.payFactor=(type,count)=>{const p=S.SYMBOLS[type].pay,raw=count<p.length?p[count]:p[p.length-1]+(count-p.length+1)*1.25;return raw*S.PAYOUT_SCALE;};
  S.clusterWin=cluster=>{const base=S.bet()*S.payFactor(cluster.type,cluster.cells.length),active=cluster.cells.map(i=>S.multiplierMap[i]).filter(Boolean),mult=active.length?active.reduce((a,b)=>a+b,0):1;return {amount:base*mult,mult};};
  S.countScatter=()=>S.grid.reduce((n,k)=>n+(k==='scatter'),0);
  S.markWins=wins=>new Set(wins.flatMap(w=>w.cells)).forEach(i=>S.els.grid.children[i]?.classList.add('win'));
  S.markVanish=wins=>new Set(wins.flatMap(w=>w.cells)).forEach(i=>{const e=S.els.grid.children[i];if(e){e.classList.remove('win');e.classList.add('vanish');}});
  S.evolveMultipliers=wins=>{S.lastMultChanges=[];const chance=S.state.freeSpins>0 ? .28 : (S.stormActive ? .24 : .15);for(const pos of new Set(wins.flatMap(w=>w.cells))){if(Math.random()>=chance)continue;const from=S.multiplierMap[pos]||0;let to;if(!from)to=Math.random()<.67?2:(Math.random()<.82?3:5);else{const idx=S.MULT_STEPS.indexOf(from);to=S.MULT_STEPS[Math.min(Math.max(0,idx)+1,S.MULT_STEPS.length-1)];}S.multiplierMap[pos]=to;if(to!==from)S.lastMultChanges.push({pos,from,to});}};
  S.collapseAndRefill=wins=>{const remove=new Set(wins.flatMap(w=>w.cells)),next=Array(S.CELL_COUNT);for(let c=0;c<S.COLS;c++){const kept=[];for(let r=S.ROWS-1;r>=0;r--){const idx=r*S.COLS+c;if(!remove.has(idx))kept.push(S.grid[idx]);}let write=S.ROWS-1;for(const sym of kept)next[write--*S.COLS+c]=sym;while(write>=0)next[write--*S.COLS+c]=S.weightedSymbol();}S.grid=next;};
  S.animateWinAmount=async(amount,cascade)=>{const text=document.createElement('div');text.className='big-win win-counter';text.innerHTML=`${S.rub(amount)}<small>ИТОГ КАСКАДА ${cascade}</small>`;S.els.overlay.replaceChildren(text);if(amount>=S.bet()*12)S.confetti(Math.min(80,18+Math.floor(amount/S.bet()*2)));await S.delay(amount>=S.bet()*10?820:520);S.els.overlay.innerHTML='';};
  S.resolveCascades=async()=>{let total=0,cascade=0;const cap=S.bet()*S.MAX_WIN_X,frame=S.$('.board-frame');while(true){const wins=S.findClusters();if(!wins.length)break;cascade++;const details=wins.map(S.clusterWin),combo=S.comboFactor?S.comboFactor(cascade):1,rawWin=details.reduce((s,x)=>s+x.amount,0)*combo,won=Math.max(0,Math.min(rawWin,cap-total));total+=won;S.state.lastWin=total;S.updateUI();S.els.cascade.textContent=`КАСКАД ${cascade}`;S.setMessage(`${wins.length===1?'КЛАСТЕР':'КЛАСТЕРЫ'} • ИТОГ +${S.rub(won)}`);if(S.showCombo)S.showCombo(cascade,combo);S.markWins(wins);frame?.classList.add('win-glow');S.sound('win',Math.min(cascade,7));if(cascade>=3){frame?.classList.add('shake');setTimeout(()=>frame?.classList.remove('shake'),380);}await S.animateWinAmount(won,cascade);frame?.classList.remove('win-glow');S.markVanish(wins);await S.delay(320);S.evolveMultipliers(wins);S.collapseAndRefill(wins);S.renderGrid({animate:true});if(S.decorateMultiplierChanges)S.decorateMultiplierChanges();await S.delay(620);if((cascade===3||cascade===6)&&S.candyBurst)await S.candyBurst(cascade);if(total>=cap){S.setMessage('ДОСТИГНУТ МАКСИМАЛЬНЫЙ ВЫИГРЫШ 25 000×');S.confetti(100);break;}if(cascade>=18)break;}S.lastCascadeCount=cascade;return total;};
  S.awardFreeSpins=n=>{if(n<3)return 0;const a=n>=5?12:n===4?10:8;S.state.freeSpins+=a;return a;};
})();
