<?php
require __DIR__.'/app/bootstrap.php';
$user=require_login();
$stmt=db()->prepare('SELECT free_spins,storm_charge,multiplier_map_json FROM user_game_states WHERE user_id=? AND game_key=? LIMIT 1');$stmt->execute([(int)$user['id'],'sweet-cascade']);$gs=$stmt->fetch();
$free=(int)($gs['free_spins']??0);$storm=(float)($gs['storm_charge']??0);$map=$gs?json_decode((string)$gs['multiplier_map_json'],true):array_fill(0,49,0);if(!is_array($map)||count($map)!==49)$map=array_fill(0,49,0);
$boot=['balance'=>(int)$user['balance_kopecks']/100,'freeSpins'=>$free,'stormCharge'=>$storm,'multiplierMap'=>$map,'csrf'=>csrf_token(),'username'=>$user['username']];
?>
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#7d1fc5"><title>Сладкий каскад — CandyClub</title><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="site.css"></head>
<body class="site-game">
<div class="cc-game-topbar"><a class="cc-back" href="index.php">← Игры</a><div class="cc-game-user"><span class="cc-virtual-pill">ВИРТУАЛЬНЫЙ БАЛАНС</span><span class="cc-mini-balance" data-site-balance><?=e(money_rub((int)$user['balance_kopecks']))?></span><a href="account.php"><?=e($user['username'])?></a></div></div>
<div class="sky-decor" aria-hidden="true"><span class="cloud c1"></span><span class="cloud c2"></span><span class="cloud c3"></span><span class="hill h1"></span><span class="hill h2"></span><span class="hill h3"></span><span class="candy-tree t1"></span><span class="candy-tree t2"></span><span class="candy-tree t3"></span></div>
<main class="game-shell">
<header class="game-header"><div class="brand" aria-label="Сладкий Каскад"><span class="brand-top">СЛАДКИЙ</span><span class="brand-main">КАСКАД</span><span class="brand-sub">МАКС</span></div><div class="headline"><strong>ВЫИГРЫШ ДО <em>25 000×</em> СТАВКИ</strong><span>Кластеры 6+ • каскады • редкие растущие множители</span></div><div class="demo-badge">ВЫСОКАЯ ВОЛАТИЛЬНОСТЬ</div></header>
<section class="game-layout">
<aside class="side-panel left-panel"><button class="feature-card buy-card" id="buyBonusBtn"><span class="feature-kicker">АКТИВИРОВАТЬ</span><strong>ФРИСПИНЫ</strong><span class="price" id="bonusPrice">8 000 ₽</span><small>8–12 бесплатных вращений</small></button><button class="feature-card super-card" id="buySuperBtn"><span class="feature-kicker">АКТИВИРОВАТЬ</span><strong>СУПЕР-БОНУС</strong><span class="price" id="superPrice">25 000 ₽</span><small>множители уже на поле</small></button><button class="mini-card" id="paytableBtn"><span>🍬</span><strong>ТАБЛИЦА ВЫПЛАТ</strong></button></aside>
<section class="board-wrap"><div class="board-topline"><span id="roundLabel">ОСНОВНАЯ ИГРА</span><span id="cascadeLabel">ГОТОВО</span></div><div class="board-frame"><div id="grid" class="slot-grid" role="grid" aria-label="Сетка 7 на 7"></div><div id="winOverlay" class="win-overlay" aria-live="polite"></div></div><div class="message-strip" id="messageStrip">УДАЧИ!</div></section>
<aside class="side-panel right-panel"><div class="info-card free-info"><span class="info-icon gumball">●</span><div><strong>ФРИСПИНЫ</strong><small>Множители сохраняются между вращениями</small></div></div><div class="info-card"><strong>ОСОБЕННОСТИ</strong><ul><li><span>⭐</span> Выигрышные кластеры от 6 символов</li><li><span>✕</span> Редкие множители до ×100</li><li><span>🎁</span> 3+ бонусов запускают фриспины</li><li><span>⚡</span> Медленнее заряжаемый Сладкий шторм</li></ul></div><div class="stats-card"><div><span>Фриспины</span><strong id="freeSpinsValue">0</strong></div><div><span>Последний выигрыш</span><strong id="lastWinValue">0 ₽</strong></div></div></aside>
</section>
<footer class="control-bar"><div class="wallet"><span>БАЛАНС</span><strong id="creditsValue">0 ₽</strong><small>сохранён на аккаунте</small></div><div class="bet-control"><button id="betMinus">−</button><div><span>СТАВКА</span><strong id="betValue">100 ₽</strong></div><button id="betPlus">+</button></div><button class="spin-button" id="spinBtn"><span class="spin-arrows">↻</span><small id="spinCaption">КРУТИТЬ</small></button><div class="control-actions"><button id="autoBtn"><span>⟳</span><small>АВТО ×20</small></button><button id="turboBtn"><span>⚡</span><small>ТУРБО</small></button><button id="soundBtn"><span id="soundIcon">🔊</span><small>ЗВУК</small></button><button id="resetBtn"><span>👤</span><small>АККАУНТ</small></button></div></footer>
<div class="legal-note">Игровой баланс виртуальный и хранится на сервере в вашем аккаунте. Денежный ввод/вывод в этой версии отсутствует.</div>
</main>
<dialog id="paytableModal" class="modal"><form method="dialog" class="modal-card"><button class="modal-close">×</button><h2>Таблица выплат</h2><p>Выигрывают группы из 6 и более одинаковых символов, соприкасающихся по вертикали или горизонтали. После выигрыша символы исчезают и запускают каскад.</p><div id="paytableList" class="paytable-list"></div><div class="rules-box"><strong>Высокая волатильность</strong><p>Кластеры, scatter и множители стали реже. Это единый профиль игры для всех аккаунтов: персональной подстройки шансов нет.</p></div><div class="rules-box"><strong>Множители клеток</strong><p>Итоговая сумма каскада уже включает все сработавшие множители. Отдельно домножать показанную сумму не нужно.</p></div><div class="rules-box"><strong>Сладкий шторм</strong><p>Шкала заряжается обычными вращениями медленнее, чем раньше. При 100% следующее платное вращение получает усиленные клетки.</p></div><div class="rules-box"><strong>Бонус</strong><p>3 бонусных символа дают 8 фриспинов, 4 — 10, 5+ — 12.</p></div></form></dialog>
<script>window.SC_BOOT=<?=json_encode($boot,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script>
<script src="game-state.js"></script><script src="game-visuals.js"></script><script src="game-juice.js"></script><script src="game-server.js"></script>
</body></html>
