(() => {
  'use strict'; const S=window.SC;
  S.neighbors=i=>{const r=Math.floor(i/S.COLS),c=i%S.COLS,out=[];if(r>0)out.push(i-S.COLS);if(r<S.ROWS-1)out.push(i+S.COLS);if(c>0)out.push(i-1);if(c<S.COLS-1)out.push(i+1);return out;};
  S.findClusters=()=>{const seen=new Set(),wins=[];for(let i=0;i<S.CELL_COUNT;i++){if(seen.has(i)||S.SYMBOLS[S.grid[i]].scatter)continue;const type=S.grid[i],stack=[i],cells=[];seen.add(i);while(stack.length){const cur=stack.pop();cells.push(cur);for(const n of S.neighbors(cur))if(!seen.has(n)&&S.grid[n]===type){seen.add(n);stack.push(n);}}if(cells.length>=5)wins.push({type,cells});}return wins;};
  S.payFactor=(type,count)=>{const p=S.SYMBOLS[type].pay,raw=count<p.length?p[count]:p[p.length-1]+(count-p.length+1)*1.25;return raw*S.PAYOUT_SCALE;};
  S.clusterWin=cluster=>{const base=S.bet()*S.payFactor(cluster.type,cluster.cells.length),active=cluster.cells.map(i=>S.multiplierMap[i]).filter(Boolean),mult=active.length?active.reduce((a,b)=>a+b,0):1;return {amount:base*mult,mult};};
  S.countScatter=()=>S.grid.reduce((n,k)=>n+(k==='scatter'),0);
  S.markWins=wins=>new Set(wins.flatMap(w=>w.cells)).forEach(i=>S.els.grid.children[i]?.classList.add('win'));
  S.markVanish=wins=>new Set(wins.flatMap(w=>w.cells)).forEach(i=>{const e=S.els.grid.children[i];if(e){e.classList.remove('win');e.classList.add('vanish');}});
  S.evolveMultipliers=wins=>{for(const pos of new Set(wins.flatMap(w=>w.cells))){if(Math.random()<(S.state.freeSpins>0?.24:.14)){const cur=S.multiplierMap[pos];if(!cur)S.multiplierMap[pos]=Math.random()<.72?2:(Math.random()<.8?3:5);else{const idx=S.MULT_STEPS.indexOf(cur);S.multiplierMap[pos]=S.MULT_STEPS[Math.min(idx+1,S.MULT_STEPS.length-1)];}}}};
  S.collapseAndRefill=wins=>{const remove=new Set(wins.flatMap(w=>w.cells)),next=Array(S.CELL_COUNT);for(let c=0;c<S.COLS;c++){const kept=[];for(let r=S.ROWS-1;r>=0;r--){const idx=r*S.COLS+c;if(!remove.has(idx))kept.push(S.grid[idx]);}let write=S.ROWS-1;for(const sym of kept)next[write--*S.COLS+c]=sym;while(write>=0)next[write--*S.COLS+c]=S.weightedSymbol();}S.grid=next;};
  S.animateWinAmount=async(amount,mult,cascade)=>{const text=document.createElement('div');text.className='big-win';text.innerHTML=`${S.rub(amount)}${mult>1?` ×${mult}`:''}<small>КАСКАД ${cascade}</small>`;S.els.overlay.replaceChildren(text);if(amount>=S.bet()*12)S.confetti(Math.min(70,18+Math.floor(amount/S.bet()*2)));await S.delay(amount>=S.bet()*10?650:380);S.els.overlay.innerHTML='';};
  S.resolveCascades=async()=>{let total=0,cascade=0;const cap=S.bet()*S.MAX_WIN_X;while(true){const wins=S.findClusters();if(!wins.length)break;cascade++;const details=wins.map(S.clusterWin),rawWin=details.reduce((s,x)=>s+x.amount,0),won=Math.max(0,Math.min(rawWin,cap-total)),topMult=Math.max(1,...details.map(x=>x.mult));total+=won;S.els.cascade.textContent=`КАСКАД ${cascade}`;S.setMessage(`${wins.length===1?'КЛАСТЕР':'КЛАСТЕРЫ'} • +${S.rub(won)}`);S.markWins(wins);S.sound('win',Math.min(cascade,7));await S.animateWinAmount(won,topMult,cascade);S.markVanish(wins);await S.delay(230);S.evolveMultipliers(wins);S.collapseAndRefill(wins);S.renderGrid({animate:true});await S.delay(470);if(total>=cap){S.setMessage('ДОСТИГНУТ МАКСИМАЛЬНЫЙ ВЫИГРЫШ 25 000×');S.confetti(100);break;}if(cascade>=18)break;}return total;};
  S.awardFreeSpins=n=>{if(n<3)return 0;const a=n>=5?12:n===4?10:8;S.state.freeSpins+=a;return a;};
})();
