<?php
require __DIR__.'/app/bootstrap.php';
require __DIR__.'/app/game_catalog.php';
$user=require_login();$game=game_config('sweet-cascade');$all=game_catalog();
$stmt=db()->prepare('SELECT free_spins,storm_charge,multiplier_map_json FROM user_game_states WHERE user_id=? AND game_key=? LIMIT 1');$stmt->execute([(int)$user['id'],'sweet-cascade']);$gs=$stmt->fetch();
$free=(int)($gs['free_spins']??0);$storm=(float)($gs['storm_charge']??0);$map=$gs?json_decode((string)$gs['multiplier_map_json'],true):array_fill(0,49,0);if(!is_array($map)||count($map)!==49)$map=array_fill(0,49,0);
$symbols=['redBear'=>['name'=>'Красный мишка'],'purpleBear'=>['name'=>'Фиолетовый мишка'],'greenStar'=>['name'=>'Зелёная звезда'],'orangeHeart'=>['name'=>'Оранжевое сердце'],'pinkDrop'=>['name'=>'Розовая капля'],'violetBean'=>['name'=>'Фиолетовая конфета'],'scatter'=>['name'=>'Подарок-бонус']];
$boot=['game'=>'sweet-cascade','title'=>$game['title'],'cols'=>7,'rows'=>7,'symbols'=>$symbols,'balance'=>(int)$user['balance_kopecks']/100,'freeSpins'=>$free,'stormCharge'=>$storm,'multiplierMap'=>$map,'csrf'=>csrf_token(),'buyBonus'=>80,'buySuper'=>250];
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#381344"><title>Сладкий каскад — CandyClub</title><link rel="stylesheet" href="<?=asset_url('arcade.css')?>"><link rel="stylesheet" href="<?=asset_url('arcade-themes.css')?>"><link rel="stylesheet" href="<?=asset_url('arcade-fx.css')?>"><link rel="stylesheet" href="<?=asset_url('arcade-pro.css')?>"></head>
<body class="arcade theme-candy game-sweet-cascade">
<header class="arc-top"><a href="index.php">← Лобби</a><span class="title">Сладкий каскад</span><span class="balance" data-balance><?=e(money_rub((int)$user['balance_kopecks']))?></span><a href="account.php"><?=e($user['username'])?></a></header>
<main class="arc-shell">
 <aside class="arc-side left">
  <div class="arc-logo" style="background:<?=e($game['accent'])?>"><span class="icon">🍬</span><strong>Сладкий каскад</strong><small>7×7 • кластеры 6+ • множители клеток</small></div>
  <button class="arc-buy-card" id="buyBtn"><span>⚡ BONUS BUY</span><strong id="buyPrice">—</strong><small>8–12 бесплатных вращений</small></button>
  <button class="arc-buy-card" id="superBuyBtn"><span>🌈 SUPER BUY</span><strong id="superBuyPrice">—</strong><small>Усиленные множители уже на поле</small></button>
  <div class="arc-info"><h3>Как играть</h3><p>Кластеры от 6 одинаковых символов исчезают и запускают каскад. Редкие клетки получают множители до ×100. Во фриспинах множители сохраняются между вращениями.</p><div class="arc-mini"><div><span>Волатильность</span><strong>Высокая</strong></div><div><span>Фриспины</span><strong id="freeValue"><?=$free?></strong></div><div><span>Последний выигрыш</span><strong id="lastWin">0 ₽</strong></div><div><span>Режим</span><strong id="modeBadge">ОСНОВНАЯ</strong></div></div><div style="margin-top:12px"><small style="color:#aaa">Заряд шторма</small><div class="sweet-storm"><i id="stormBar" style="width:<?=max(0,min(100,$storm))?>%"></i></div></div></div>
 </aside>
 <section class="arc-stage"><div class="arc-card"><div class="arc-status"><span id="statusLeft">ГОТОВО</span><span id="statusRight">КЛАСТЕРЫ 6+ • КАСКАДЫ</span></div><div class="arc-board-frame"><div id="arcBoard" class="arc-board" style="--cols:7;--rows:7;grid-template-columns:repeat(7,1fr);grid-template-rows:repeat(7,1fr)"></div><div id="arcOverlay" class="arc-overlay"></div></div><div id="arcMessage" class="arc-message">УДАЧИ!</div><div id="featureBox"></div><div class="arc-controls"><div class="arc-wallet"><span>Баланс</span><strong id="walletValue"><?=e(money_rub((int)$user['balance_kopecks']))?></strong></div><div class="arc-bet"><button id="betMinus">−</button><div><span>Ставка</span><strong id="betValue">100 ₽</strong></div><button id="betPlus">+</button></div><button id="spinBtn" class="arc-spin"><span>↻</span><small>SPIN</small></button><div class="arc-actions"><button id="autoBtn" class="arc-action">АВТО ×20</button><button id="turboBtn" class="arc-action">⚡ ТУРБО</button><button id="soundBtn" class="arc-action">🔊 ЗВУК</button></div></div></div></section>
 <aside class="arc-side right"><h3 style="margin-top:3px">Другие слоты</h3><div class="arc-game-list"><?php foreach($all as $slug=>$g): $href=$slug==='sweet-cascade'?'game.php':$g['route']; ?><a class="arc-game-link <?=$slug==='sweet-cascade'?'current':''?>" href="<?=e($href)?>"><i style="background:<?=e($g['accent'])?>"><?=e($g['icon'])?></i><div><strong><?=e($g['title'])?></strong><small><?=e($g['subtitle'])?></small></div></a><?php endforeach; ?></div><a class="arc-mini-link" href="mini.php?game=plinko">● Плинко</a><a class="arc-mini-link" href="mini.php?game=mines">◆ Мины</a><a class="arc-mini-link" href="mini.php?game=wheel">◉ Колесо</a><p class="arc-rules">Все суммы виртуальные. Сладкий каскад использует тот же серверный баланс и историю раундов, что и остальные игры.</p></aside>
</main>
<script>window.SWEET_BOOT=<?=json_encode($boot,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script><script src="<?=asset_url('arcade-symbols.js')?>"></script><script src="<?=asset_url('sweet-arcade.js')?>"></script>
</body></html>
