<?php
declare(strict_types=1);
header('Content-Type: text/html; charset=utf-8');
$version=PHP_VERSION;$versionOk=version_compare(PHP_VERSION,'8.2.0','>=');$configFile=__DIR__.'/app/config.php';$configExists=is_file($configFile);$pdoExt=extension_loaded('pdo');$pdoMysql=extension_loaded('pdo_mysql');$mb=extension_loaded('mbstring');$json=extension_loaded('json');
$required=['app/bootstrap.php','app/game_catalog.php','app/arcade_v2.php','app/feature_slots.php','app/mini_games.php','arcade-symbols.js','arcade-game.js','sweet-arcade.js','mini-games.js','lobby.js','arcade-pro.css','ecosystem.css','mini.css','api/mini.php'];$missing=[];foreach($required as $f)if(!is_file(__DIR__.'/'.$f))$missing[]=$f;
$dbOk=false;$tablesOk=false;$dbMessage=$configExists?'Не проверено':'Нужен config.php';
if($configExists&&$pdoMysql){
 try{$cfg=require $configFile;$d=$cfg['db']??[];$dsn=sprintf('mysql:host=%s;dbname=%s;charset=%s',$d['host']??'localhost',$d['name']??'',$d['charset']??'utf8mb4');$check=new PDO($dsn,$d['user']??'',$d['pass']??'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$dbOk=true;$dbMessage='Подключение OK';$need=['users','wallet_transactions','user_game_states','game_rounds'];$found=$check->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);$tablesOk=count(array_diff($need,$found))===0;if(!$tablesOk)$dbMessage='Подключение есть, но не все таблицы импортированы';}catch(Throwable $e){$dbMessage='Ошибка подключения';}
}
$allOk=$versionOk&&$configExists&&$pdoExt&&$pdoMysql&&$mb&&$json&&!$missing&&$dbOk&&$tablesOk;
function row(string $name,bool $ok,string $value): string{return '<div class="row"><span>'.htmlspecialchars($name).'</span><strong class="'.($ok?'ok':'bad').'">'.htmlspecialchars($value).'</strong></div>';}
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CandyClub — диагностика</title><style>body{font-family:system-ui;background:#0f0d18;color:#fff;margin:0;padding:28px}.card{max-width:820px;margin:auto;background:#1d1829;border:1px solid #453b58;border-radius:22px;padding:24px;box-shadow:0 25px 70px #0006}h1{margin:0 0 6px}.lead{color:#aaa0b8;margin:0 0 18px}.status{padding:12px 14px;border-radius:14px;margin:14px 0;font-weight:900}.status.ok{background:#193b2b;color:#8bf2af}.status.bad{background:#49202d;color:#ff9fb0}.row{display:flex;justify-content:space-between;gap:20px;padding:11px 0;border-bottom:1px solid #392f48}.ok{color:#72efa0}.bad{color:#ff8ca4}code{background:#322a42;padding:3px 7px;border-radius:7px}p{color:#c8bfd1;line-height:1.55}.missing{padding:12px;border-radius:12px;background:#271d32;color:#ffb2c0;font:12px ui-monospace,monospace;margin-top:12px}a{color:#ddb4ff}</style></head><body><div class="card"><h1>Диагностика CandyClub</h1><p class="lead">Проверка окружения после загрузки проекта на хостинг.</p><div class="status <?=$allOk?'ok':'bad'?>"><?=$allOk?'Система готова к запуску':'Есть пункты, требующие внимания'?></div><?=row('Версия PHP',$versionOk,$version)?><?=row('PHP 8.2+',$versionOk,$versionOk?'OK':'Нужно переключить')?><?=row('PDO',$pdoExt,$pdoExt?'OK':'Нет')?><?=row('PDO MySQL',$pdoMysql,$pdoMysql?'OK':'Нет')?><?=row('mbstring',$mb,$mb?'OK':'Нет')?><?=row('JSON',$json,$json?'OK':'Нет')?><?=row('app/config.php',$configExists,$configExists?'Найден':'Не создан')?><?=row('Обязательные модули',!$missing,$missing?'Не все загружены':'Все найдены')?><?=row('MySQL',$dbOk,$dbMessage)?><?=row('Таблицы БД',$tablesOk,$tablesOk?'Все найдены':'Проверьте schema.sql')?><?php if($missing): ?><div class="missing">Отсутствуют: <?=htmlspecialchars(implode(', ',$missing))?></div><?php endif; ?><p>При чистой установке скопируйте <code>app/config.example.php</code> в <code>app/config.php</code> и импортируйте <code>schema.sql</code>. При обновлении существующей установки повторный импорт схемы не требуется.</p><p><a href="/">← Вернуться в лобби</a></p></div></body></html>
