<?php
header('Content-Type: text/html; charset=utf-8');
$version = PHP_VERSION;
$versionOk = version_compare(PHP_VERSION, '8.1.0', '>=');
$configExists = is_file(__DIR__ . '/app/config.php');
$pdo = extension_loaded('pdo');
$pdoMysql = extension_loaded('pdo_mysql');
$mb = extension_loaded('mbstring');
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CandyClub — диагностика</title><style>body{font-family:system-ui;background:#130e1b;color:#fff;margin:0;padding:28px}.card{max-width:760px;margin:auto;background:#21182c;border:1px solid #453650;border-radius:20px;padding:22px}h1{margin-top:0}.row{display:flex;justify-content:space-between;gap:20px;padding:11px 0;border-bottom:1px solid #3b2d45}.ok{color:#72efa0}.bad{color:#ff8ca4}code{background:#32243d;padding:3px 7px;border-radius:7px}p{color:#c8b9d1;line-height:1.55}</style></head><body><div class="card"><h1>Диагностика CandyClub</h1><div class="row"><span>Версия PHP</span><strong class="<?=$versionOk?'ok':'bad'?>"><?=htmlspecialchars($version)?></strong></div><div class="row"><span>PHP 8.1+</span><strong class="<?=$versionOk?'ok':'bad'?>"><?=$versionOk?'OK':'Нужно переключить'?></strong></div><div class="row"><span>PDO</span><strong class="<?=$pdo?'ok':'bad'?>"><?=$pdo?'OK':'Нет'?></strong></div><div class="row"><span>PDO MySQL</span><strong class="<?=$pdoMysql?'ok':'bad'?>"><?=$pdoMysql?'OK':'Нет'?></strong></div><div class="row"><span>mbstring</span><strong class="<?=$mb?'ok':'bad'?>"><?=$mb?'OK':'Нет'?></strong></div><div class="row"><span>app/config.php</span><strong class="<?=$configExists?'ok':'bad'?>"><?=$configExists?'Найден':'Не создан'?></strong></div><p>Для проекта рекомендуется PHP <strong>8.2 или 8.3</strong>. Если конфиг не создан, скопируйте <code>app/config.example.php</code> в <code>app/config.php</code>, заполните данные MySQL и импортируйте <code>schema.sql</code>.</p><p><a style="color:#ddadff" href="/">Вернуться на главную</a></p></div></body></html>
