<?php
require __DIR__.'/app/bootstrap.php';
require __DIR__.'/app/views.php';
require __DIR__.'/app/game_catalog.php';
require __DIR__.'/app/mini_games.php';
require __DIR__.'/app/mini_expansion.php';
require __DIR__.'/app/mini_catalog.php';
$user=current_user();$games=game_catalog();$minis=mini_catalog();$uid=$user?(int)$user['id']:0;$progress=$user?player_progress($uid):null;$division=$user?cc_division($progress['level']):null;$daily=$user?daily_reward_status_v2(db(),$uid):['available'=>false,'streak'=>0,'next_day'=>1,'next_bonus'=>75];$missions=$user?cc_daily_missions($uid):[];$profile=$user?cc_profile_state($uid):cc_profile_defaults();$personalRecent=$user?cc_recent_games($uid,4):[];
$recent=db()->query("SELECT r.game_key,r.bet_kopecks,r.win_kopecks,r.created_at,u.username FROM game_rounds r JOIN users u ON u.id=r.user_id WHERE r.win_kopecks>0 ORDER BY r.id DESC LIMIT 8")->fetchAll();
function lobby_recent_meta(string $key,array $games,array $minis): array {if(str_starts_with($key,'mini-')){$m=substr($key,5);if(isset($minis[$m]))return[$minis[$m]['title'],$minis[$m]['icon'],'mini.php?game='.rawurlencode($m)];return[$key,'•','index.php#mini'];}if(isset($games[$key]))return[$games[$key]['title'],$games[$key]['icon'],$key==='sweet-cascade'?'game.php':$games[$key]['route']];return[$key,'•','index.php'];}
site_head('CandyClub — игровая экосистема');echo '<body class="cc-site">';site_nav($user);
?>
<main>
<section class="cc-container cc-hero-v2">
 <div class="cc-hero-copy"><span class="cc-kicker"><?=count($games)?> оригинальных слотов • <?=count($minis)?> мини-игр • клуб и миссии</span><h1>Своя игровая <em>экосистема.</em></h1><p>Кластеры, scatter pays, ways, tumble, hold-and-respin, mystery-блоки, полные wild-колонны, шестерни, множители и многошаговые мини-игры. Результаты рассчитываются сервером, а прогресс объединён в одном аккаунте.</p><div class="cc-hero-actions"><?php if($user): ?><a class="cc-btn cc-btn-primary" href="play.php?game=forge-tempest">Играть сейчас</a><a class="cc-btn" href="club.php">Клуб игрока</a><a class="cc-btn" href="#mini">Мини-игры</a><?php else: ?><a class="cc-btn cc-btn-primary" href="register.php">Создать аккаунт</a><a class="cc-btn" href="login.php">Войти</a><?php endif; ?></div></div>
 <aside class="cc-dashboard-card">
 <?php if($user): ?>
  <div><div class="cc-level-row"><div class="cc-level-badge"><?=e($division['icon'])?></div><div><strong><?=e($user['username'])?></strong><small><?=e($division['name'])?> • уровень <?=$progress['level']?> • <?=$progress['xp']?> XP</small></div></div><div class="cc-xp"><i style="width:<?=round($progress['progress'],1)?>%"></i></div><div class="cc-dashboard-stats"><div><span>Раунды</span><strong><?=number_format($progress['rounds'],0,',',' ')?></strong></div><div><span>Лучшая победа</span><strong><?=e(money_rub($progress['best_win']))?></strong></div><div><span>Баланс</span><strong><?=e(money_rub((int)$user['balance_kopecks']))?></strong></div></div></div>
  <div class="cc-daily"><div class="cc-daily-icon">🎁</div><div><strong>Серия подарков • день <?=e((string)$daily['next_day'])?>/7</strong><small><?=$daily['available']?'Сегодня +'.e(money_rub((int)round($daily['next_bonus']*100))):'Сегодня получено • серия '.(int)$daily['streak'].' дн.'?></small></div><button id="dailyBtn" <?=$daily['available']?'':'disabled'?>><?=$daily['available']?'ЗАБРАТЬ':'ПОЛУЧЕНО'?></button></div>
 <?php else: ?><div><div class="cc-level-row"><div class="cc-level-badge">1</div><div><strong>Гостевой режим</strong><small>Создайте аккаунт, чтобы сохранять прогресс</small></div></div><div class="cc-dashboard-stats" style="margin-top:18px"><div><span>Слоты</span><strong><?=count($games)?></strong></div><div><span>Мини-игры</span><strong><?=count($minis)?></strong></div><div><span>Баланс</span><strong>после регистрации</strong></div></div></div><a class="cc-btn cc-btn-primary" href="register.php">Начать</a><?php endif; ?>
 </aside>
</section>
<?php if($user&&$personalRecent): ?><section class="cc-section compact"><div class="cc-container"><div class="cc-section-head"><div><h2>Продолжить игру</h2><p>Последние режимы вашего аккаунта.</p></div><a class="cc-btn" href="club.php">Весь прогресс</a></div><div class="cc-continue-grid"><?php foreach($personalRecent as $r): [$t,$ic,$href]=lobby_recent_meta((string)$r['game_key'],$games,$minis); ?><a href="<?=e($href)?>"><i><?=e($ic)?></i><div><strong><?=e($t)?></strong><small><?=$r['rounds']?> раундов • <?=e(date('d.m H:i',strtotime($r['last_played'])))?></small></div><span>Продолжить →</span></a><?php endforeach; ?></div></div></section><?php endif; ?>
<section class="cc-section" id="slots"><div class="cc-container"><div class="cc-section-head"><div><h2>Слоты</h2><p><?=count($games)?> игр с разной математикой, темпом и бонусной логикой.</p></div></div><div class="cc-toolbar"><input class="cc-search" id="gameSearch" placeholder="Найти игру или механику…"><button class="cc-filter active" data-filter="all">Все</button><button class="cc-filter" data-filter="Buy Bonus">Buy Bonus</button><button class="cc-filter" data-filter="Каскады">Каскады</button><button class="cc-filter" data-filter="favorites">★ Избранное</button></div><div class="cc-slot-grid" id="slotGrid">
<?php foreach($games as $slug=>$g): $href=$user?$g['route']:'login.php';$tags=$g['tags']??[]; ?><a class="cc-slot-card" href="<?=e($href)?>" data-game="<?=e(mb_strtolower($g['title'].' '.$g['subtitle'].' '.implode(' ',$tags)))?>" data-tags="<?=e(implode('|',$tags))?>" data-key="<?=e($slug)?>"><div class="cc-slot-art" style="background:<?=e($g['accent'])?>"><span class="cc-slot-badge"><?=e($g['volatility']??'Высокая')?> волатильность</span><button class="cc-fav" type="button" data-fav="<?=e($slug)?>" aria-label="В избранное">★</button><span class="cc-slot-icon"><?=e($g['icon'])?></span></div><div class="cc-slot-meta"><strong><?=e($g['title'])?></strong><small><?=e($g['subtitle'])?></small><div class="cc-tags"><?php foreach($tags as $tag): ?><span><?=e($tag)?></span><?php endforeach; ?></div></div></a><?php endforeach; ?>
</div></div></section>
<section class="cc-section" id="mini"><div class="cc-container"><div class="cc-section-head"><div><h2>Мини-игры</h2><p><?=count($minis)?> самостоятельных режимов — от мгновенных бросков до сохраняемых многошаговых партий.</p></div></div><div class="cc-mini-grid"><?php foreach($minis as $slug=>$m): ?><a class="cc-mini-card <?=e($m['class']??$slug)?>" href="<?=$user?'mini.php?game='.e($slug):'login.php'?>"><span class="icon"><?=e($m['icon'])?></span><div><h3><?=e($m['title'])?></h3><p><?=e($m['subtitle'])?></p></div></a><?php endforeach; ?></div></div></section>
<section class="cc-section"><div class="cc-container cc-live-grid"><div class="cc-live-card"><div class="cc-section-head"><div><h2 style="font-size:22px">Последние выигрыши</h2><p>Обезличенная активность платформы.</p></div></div><div class="cc-live-list"><?php if(!$recent): ?><div class="cc-empty">Пока нет выигрышных раундов.</div><?php else: foreach($recent as $r): ?><div class="cc-live-item"><i>✦</i><div><strong><?=e(cc_mask_name((string)$r['username']))?> • <?=e(str_replace(['mini-','-'],['',' '],(string)$r['game_key']))?></strong><small><?=e(date('H:i',strtotime($r['created_at'])))?> • ставка <?=e(money_rub((int)$r['bet_kopecks']))?></small></div><b>+<?=e(money_rub((int)$r['win_kopecks']))?></b></div><?php endforeach; endif; ?></div></div><div class="cc-missions"><h2 style="font-size:22px;margin-top:0">Миссии сегодня</h2><?php if($user): foreach(array_slice($missions,0,3) as $m): ?><div class="cc-mission"><strong><?=e($m['title'])?> <?=$m['claimed']?'✓':''?></strong><small><?=e($m['description'])?></small><div class="cc-progress"><i style="width:<?=round($m['progress'])?>%"></i></div></div><?php endforeach; ?><a class="cc-btn" style="margin-top:10px;width:100%" href="club.php">Открыть клуб и награды</a><?php else: ?><p style="color:var(--cc-muted)">После регистрации появятся ежедневные миссии, достижения и дивизионы.</p><?php endif; ?></div></div></section>
</main>
<script>window.LOBBY_BOOT=<?=json_encode(['csrf'=>csrf_token(),'loggedIn'=>(bool)$user,'favorites'=>$profile['favorites']??[],'daily'=>$daily],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script><script src="<?=asset_url('lobby.js')?>"></script>
<?php site_footer(); ?>
