(function(){
'use strict';
var B=window.LOBBY_BOOT||{},search=document.getElementById('gameSearch'),cards=Array.prototype.slice.call(document.querySelectorAll('.cc-slot-card')),filters=Array.prototype.slice.call(document.querySelectorAll('.cc-filter')),activeFilter='all',favs=[];
function rid(){try{return crypto.randomUUID().replace(/-/g,'')}catch(e){return Date.now().toString(36)+Math.random().toString(36).slice(2)}}
if(B.loggedIn&&Array.isArray(B.favorites))favs=B.favorites.slice();else try{favs=JSON.parse(localStorage.getItem('ccFavorites')||'[]');if(!Array.isArray(favs))favs=[]}catch(e){favs=[]}
function toast(t){var e=document.createElement('div');e.className='cc-toast-global';e.textContent=t;document.body.appendChild(e);setTimeout(function(){e.remove()},2700)}
function paintFavs(){var btns=document.querySelectorAll('.cc-fav');for(var i=0;i<btns.length;i++)btns[i].classList.toggle('active',favs.indexOf(btns[i].getAttribute('data-fav'))>=0)}
function apply(){var term=(search?search.value:'').trim().toLowerCase();cards.forEach(function(card){var text=card.getAttribute('data-game')||'',tags=card.getAttribute('data-tags')||'',key=card.getAttribute('data-key')||'';var okTerm=!term||text.indexOf(term)>=0;var okFilter=activeFilter==='all'||(activeFilter==='favorites'?favs.indexOf(key)>=0:tags.indexOf(activeFilter)>=0);card.style.display=okTerm&&okFilter?'':'none'})}
if(search)search.addEventListener('input',apply);filters.forEach(function(b){b.addEventListener('click',function(){activeFilter=b.getAttribute('data-filter')||'all';filters.forEach(function(x){x.classList.remove('active')});b.classList.add('active');apply()})});
async function toggleServer(k){var r=await fetch('api/club.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-Token':B.csrf},body:JSON.stringify({action:'favorite_toggle',game:k})});var d=await r.json().catch(function(){return{ok:false,error:'Ошибка ответа.'}});if(!r.ok||!d.ok)throw new Error(d.error||'Не удалось сохранить избранное.');return d.favorites||[]}
Array.prototype.slice.call(document.querySelectorAll('.cc-fav')).forEach(function(b){b.addEventListener('click',async function(e){e.preventDefault();e.stopPropagation();var k=b.getAttribute('data-fav'),was=favs.indexOf(k)>=0;b.disabled=true;try{if(B.loggedIn)favs=await toggleServer(k);else{var i=favs.indexOf(k);if(i>=0)favs.splice(i,1);else favs.push(k);try{localStorage.setItem('ccFavorites',JSON.stringify(favs))}catch(err){}}paintFavs();apply();toast(was?'Удалено из избранного':'Добавлено в избранное')}catch(err){toast(err.message)}finally{b.disabled=false}})});paintFavs();apply();
var daily=document.getElementById('dailyBtn');if(daily)daily.addEventListener('click',async function(){if(daily.disabled)return;daily.disabled=true;daily.textContent='…';try{var r=await fetch('api/mini.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-Token':B.csrf},body:JSON.stringify({game:'daily',action:'claim',request_id:rid()})});var d=await r.json().catch(function(){return{ok:false,error:'Ошибка ответа.'}});if(!r.ok||!d.ok)throw new Error(d.error||'Не удалось получить подарок.');daily.textContent='ПОЛУЧЕНО';var bal=document.querySelector('.cc-balance strong');if(bal)bal.textContent=new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB'}).format(d.balance_after);var card=daily.closest('.cc-daily'),small=card?card.querySelector('small'):null,strong=card?card.querySelector('strong'):null;if(small)small.textContent='Получено сегодня • серия '+Number(d.streak||d.day||1)+' дн.';if(strong)strong.textContent='Серия подарков • день '+Number(d.day||1)+'/7';toast('🎁 День '+Number(d.day||1)+'/7: +'+new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB'}).format(d.bonus)+(d.cycle_complete?' • цикл завершён!':''))}catch(e){daily.disabled=false;daily.textContent='ЗАБРАТЬ';toast(e.message)}});
})();
