(function(){
'use strict';
var B=window.MINI_BOOT||{};var box=document.getElementById('miniGameBox');var bets=[10,20,50,100,200,500,1000];var betIndex=3;var busy=false;var balance=Number(B.balance||0);var audio=null;var selectedMines=5;var activeMines=B.activeMines||null;
function q(s){return document.querySelector(s)}function delay(ms){return new Promise(function(r){setTimeout(r,ms)})}function rub(v){return new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:(v%1?2:0)}).format(v)}function bet(){return bets[betIndex]}
function sound(kind){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();var now=audio.currentTime;function hit(f,t,d,g,type){var o=audio.createOscillator(),a=audio.createGain();o.type=type||'sine';o.frequency.value=f;a.gain.setValueAtTime(.001,now+t);a.gain.linearRampToValueAtTime(g||.035,now+t+.01);a.gain.exponentialRampToValueAtTime(.001,now+t+(d||.15));o.connect(a).connect(audio.destination);o.start(now+t);o.stop(now+t+(d||.15)+.03)}if(kind==='tick')hit(340,0,.06,.02,'triangle');if(kind==='peg')hit(540,0,.05,.018,'sine');if(kind==='good'){hit(520,0,.12,.035);hit(760,.08,.15,.04);hit(980,.17,.18,.045)}if(kind==='bad'){hit(120,0,.2,.04,'sawtooth');hit(82,.1,.22,.03,'sawtooth')}if(kind==='cash'){[420,560,720,930].forEach(function(f,i){hit(f,i*.07,.18,.035)})}}catch(e){}}
function update(){q('#betValue').textContent=rub(bet());q('#topBalance').textContent=rub(balance);q('#sideBalance').textContent=rub(balance)}
function status(t){q('#miniStatus').textContent=t}function result(label,win){q('#lastResult').textContent=label;q('#lastWin').textContent=rub(win||0)}
async function api(payload){var r=await fetch('api/mini.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-Token':B.csrf},body:JSON.stringify(payload)});var d=await r.json().catch(function(){return{ok:false,error:'Некорректный ответ сервера.'}});if(!r.ok||!d.ok)throw new Error(d.error||'Ошибка мини-игры.');return d}
function setBusy(v){busy=v;q('#playBtn').disabled=v||!!activeMines;q('#betMinus').disabled=v||!!activeMines;q('#betPlus').disabled=v||!!activeMines;var opts=document.querySelectorAll('#mineOptions button');for(var i=0;i<opts.length;i++)opts[i].disabled=v||!!activeMines}
function renderPlinko(){var html='<div class="plinko-wrap"><div class="plinko-board" id="plinkoBoard"></div><div class="plinko-bins" id="plinkoBins"></div></div>';box.innerHTML=html;var board=q('#plinkoBoard');for(var row=0;row<12;row++){var count=row+3;for(var j=0;j<count;j++){var p=document.createElement('i');p.className='plinko-peg';p.style.left=((j+1)/(count+1)*100)+'%';p.style.top=((row+1)/13*100)+'%';board.appendChild(p)}}var mult=[8,3,1.8,1.15,.75,.48,.32,.48,.75,1.15,1.8,3,8],bins=q('#plinkoBins');mult.forEach(function(m){var e=document.createElement('div');e.className='plinko-bin'+(m>=3?' hot':'');e.textContent=m+'×';bins.appendChild(e)})}
async function playPlinko(){if(busy)return;setBusy(true);status('РАСЧЁТ');try{var d=await api({game:'plinko',action:'play',bet:bet()});balance=d.balance_before-d.bet;update();var board=q('#plinkoBoard');var ball=document.createElement('i');ball.className='plinko-ball';board.appendChild(ball);var x=.5,top=0;ball.style.left='50%';ball.style.top='0%';await delay(120);for(var i=0;i<d.path.length;i++){var spread=.5/(i+3);x+=d.path[i]?spread:-spread;x=Math.max(.04,Math.min(.96,x));top=(i+1)/13;ball.style.left=(x*100)+'%';ball.style.top=(top*100)+'%';sound('peg');await delay(135)}ball.style.left=((d.bin+.5)/13*100)+'%';ball.style.top='106%';await delay(170);var bin=q('#plinkoBins').children[d.bin];if(bin)bin.classList.add('hit');sound(d.multiplier>=1?'good':'bad');balance=Number(d.balance_after);update();result(d.multiplier+'×',Number(d.win));status('ГОТОВО');await delay(650);ball.remove()}catch(e){status('ОШИБКА');result(e.message,0)}setBusy(false)}
function renderWheel(){var segs=['0×','.4×','.6×','.8×','1×','1.2×','1.5×','2×','3×','5×'];var colors=['#50233d','#66395f','#304875','#365c6d','#23664f','#3c6b36','#766b2d','#7a4a2d','#7a2f42','#612d83'];var stops=[];for(var i=0;i<segs.length;i++)stops.push(colors[i]+' '+(i*36)+'deg '+((i+1)*36)+'deg');box.innerHTML='<div class="wheel-wrap"><div class="wheel-pointer"></div><div class="wheel-disc" id="wheelDisc" style="background:conic-gradient('+stops.join(',')+')"></div></div>';var disc=q('#wheelDisc');segs.forEach(function(s,i){var e=document.createElement('span');e.className='wheel-label';e.textContent=s;e.style.transform='rotate('+(i*36+18)+'deg) translateY(-6px)';disc.appendChild(e)})}
async function playWheel(){if(busy)return;setBusy(true);status('РАЗГОН');try{var d=await api({game:'wheel',action:'play',bet:bet()});balance=d.balance_before-d.bet;update();var disc=q('#wheelDisc');var turns=5+Math.floor(Math.random()*2),angle=turns*360+(360-(d.segment*36+18));disc.style.transform='rotate('+angle+'deg)';for(var i=0;i<28;i++){sound('tick');await delay(55+i*5)}await delay(2200);sound(d.multiplier>=1?'good':'bad');balance=Number(d.balance_after);update();result(d.multiplier+'×',Number(d.win));status('ГОТОВО')}catch(e){status('ОШИБКА');result(e.message,0)}setBusy(false)}
function renderMines(){box.innerHTML='<div class="mines-wrap"><div class="mines-grid" id="minesGrid"></div><div class="mini-result" id="minesResult" style="margin-top:18px">1.00×<small>ТЕКУЩИЙ МНОЖИТЕЛЬ</small></div></div>';var g=q('#minesGrid');for(var i=0;i<25;i++){var b=document.createElement('button');b.type='button';b.className='mine-cell';b.setAttribute('data-cell',String(i));b.addEventListener('click',revealMine);g.appendChild(b)}if(activeMines){selectedMines=Number(activeMines.mines||5);var opts=document.querySelectorAll('#mineOptions button');for(var j=0;j<opts.length;j++)opts[j].classList.toggle('active',Number(opts[j].getAttribute('data-mines'))===selectedMines);(activeMines.opened||[]).forEach(function(i){if(g.children[i]){g.children[i].classList.add('safe');g.children[i].disabled=true}});q('#minesResult').firstChild.nodeValue=Number(activeMines.multiplier||1).toFixed(2)+'×';q('#playBtn').textContent='ИГРА ИДЁТ';q('#cashBtn').disabled=(activeMines.opened||[]).length===0;status('АКТИВНА')}else{q('#playBtn').textContent='НАЧАТЬ';q('#cashBtn').disabled=true}setBusy(false)}
async function startMines(){if(busy||activeMines)return;setBusy(true);status('ПОДГОТОВКА');try{var d=await api({game:'mines',action:'start',bet:bet(),mines:selectedMines});balance=Number(d.balance_after);activeMines={bet:d.bet,mines:d.mines,opened:[],multiplier:1};update();renderMines();status('ВЫБЕРИТЕ КЛЕТКУ')}catch(e){status('ОШИБКА');result(e.message,0);setBusy(false)}}
async function finishMines(d,auto){sound('cash');if(d.balance_after!=null){balance=Number(d.balance_after);update()}var g=q('#minesGrid');(d.opened||[]).forEach(function(i){if(g.children[i]){g.children[i].classList.add('safe');g.children[i].disabled=true}});(d.mine_cells||[]).forEach(function(i){var c=g.children[i];if(c&&!c.classList.contains('safe')){c.classList.add('mine');c.disabled=true}});result(Number(d.multiplier||0).toFixed(2)+'×',Number(d.win||0));q('#minesResult').firstChild.nodeValue=Number(d.multiplier||0).toFixed(2)+'×';activeMines=null;q('#cashBtn').disabled=true;q('#playBtn').textContent='НАЧАТЬ';status(auto?'ПОЛЕ ОЧИЩЕНО':'ВЫИГРЫШ');await delay(1100);renderMines()}
async function revealMine(ev){if(busy||!activeMines)return;var el=ev.currentTarget,cell=Number(el.getAttribute('data-cell'));busy=true;try{var d=await api({game:'mines',action:'reveal',cell:cell});if(d.state==='lost'){el.classList.add('mine');sound('bad');(d.mine_cells||[]).forEach(function(i){var c=q('#minesGrid').children[i];if(c){c.classList.add('mine');c.disabled=true}});activeMines=null;q('#cashBtn').disabled=true;q('#playBtn').textContent='НАЧАТЬ';q('#minesResult').firstChild.nodeValue='0.00×';result('МИНА',0);status('ПРОИГРЫШ');await delay(900);renderMines();busy=false;return}if(d.state==='cashed'){el.classList.add('safe');await finishMines(d,true);busy=false;return}el.classList.add('safe');el.disabled=true;sound('good');activeMines.opened=d.opened;activeMines.multiplier=d.multiplier;q('#minesResult').firstChild.nodeValue=Number(d.multiplier).toFixed(2)+'×';q('#cashBtn').disabled=false;result(Number(d.multiplier).toFixed(2)+'×',Number(d.potential_win||0));status('МОЖНО ЗАБРАТЬ')}catch(e){status('ОШИБКА');result(e.message,0)}busy=false}
async function cashMines(){if(busy||!activeMines)return;busy=true;q('#cashBtn').disabled=true;status('ЗАБИРАЕМ');try{var d=await api({game:'mines',action:'cashout'});await finishMines(d,false);busy=false}catch(e){status('ОШИБКА');result(e.message,0);busy=false;q('#cashBtn').disabled=false}}
q('#betMinus').addEventListener('click',function(){if(!busy&&!activeMines){betIndex=Math.max(0,betIndex-1);update();sound('tick')}});q('#betPlus').addEventListener('click',function(){if(!busy&&!activeMines){betIndex=Math.min(bets.length-1,betIndex+1);update();sound('tick')}});
if(B.game==='plinko'){renderPlinko();q('#playBtn').addEventListener('click',playPlinko)}else if(B.game==='wheel'){renderWheel();q('#playBtn').addEventListener('click',playWheel)}else{renderMines();q('#playBtn').addEventListener('click',startMines);q('#cashBtn').addEventListener('click',cashMines);var mo=document.querySelectorAll('#mineOptions button');for(var i=0;i<mo.length;i++)mo[i].addEventListener('click',function(){if(activeMines)return;selectedMines=Number(this.getAttribute('data-mines'));for(var j=0;j<mo.length;j++)mo[j].classList.remove('active');this.classList.add('active');sound('tick')})}
update();
})();
