<?php
require __DIR__.'/app/bootstrap.php';
require __DIR__.'/app/game_catalog.php';
$user=require_login();
$key=(string)($_GET['game']??'');$game=game_config($key);
if(!$game||$key==='sweet-cascade'){header('Location: game.php');exit;}
$stmt=db()->prepare('SELECT free_spins,multiplier_map_json FROM user_game_states WHERE user_id=? AND game_key=? LIMIT 1');$stmt->execute([(int)$user['id'],$key]);$gs=$stmt->fetch();$free=(int)($gs['free_spins']??0);$state=$gs?json_decode((string)$gs['multiplier_map_json'],true):[];if(!is_array($state))$state=[];
$boot=['game'=>$key,'title'=>$game['title'],'cols'=>$game['cols'],'rows'=>$game['rows'],'symbols'=>$game['symbols'],'balance'=>(int)$user['balance_kopecks']/100,'freeSpins'=>$free,'state'=>$state,'csrf'=>csrf_token(),'rules'=>$game['rules'],'accent'=>$game['accent'],'theme'=>$game['theme'],'volatility'=>$game['volatility']??'Высокая','buyBonus'=>(int)($game['buy_bonus']??0)];
$all=game_catalog();
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#100c16"><title><?=e($game['title'])?> — CandyClub</title><link rel="stylesheet" href="<?=asset_url('arcade.css')?>"><link rel="stylesheet" href="<?=asset_url('arcade-themes.css')?>"><link rel="stylesheet" href="<?=asset_url('arcade-fx.css')?>"><link rel="stylesheet" href="<?=asset_url('arcade-pro.css')?>"></head>
<body class="arcade theme-<?=e($game['theme'])?> game-<?=e($key)?>" style="--accent:<?=e($game['accent'])?>">
<header class="arc-top"><a href="index.php">← Лобби</a><span class="title"><?=e($game['title'])?></span><span class="balance" data-balance><?=e(money_rub((int)$user['balance_kopecks']))?></span><a href="account.php"><?=e($user['username'])?></a></header>
<main class="arc-shell">
  <aside class="arc-side left">
    <div class="arc-logo" style="--accent:<?=e($game['accent'])?>;background:<?=e($game['accent'])?>"><span class="icon"><?=e($game['icon'])?></span><strong><?=e($game['title'])?></strong><small><?=e($game['subtitle'])?></small></div>
    <?php if(!empty($game['buy_bonus'])): ?><button class="arc-buy-card" id="buyBtn"><span>⚡ BONUS BUY</span><strong id="buyPrice">—</strong><small><?=$key==='jungle-hold'?'Сразу открыть Hold & Respin':'Сразу запустить бонусную серию'?></small></button><?php endif; ?>
    <div class="arc-info"><h3>Как играть</h3><p><?=e($game['rules'])?></p><div class="arc-mini"><div><span>Волатильность</span><strong><?=e($game['volatility']??'Высокая')?></strong></div><div><span>Фриспины</span><strong id="freeValue"><?=$free?></strong></div><div><span>Последний выигрыш</span><strong id="lastWin">0 ₽</strong></div><div><span>Режим</span><strong id="modeBadge">ОСНОВНАЯ</strong></div></div></div>
  </aside>
  <section class="arc-stage"><div class="arc-card"><div class="arc-status"><span id="statusLeft">ГОТОВО</span><span id="statusRight"><?=e($game['subtitle'])?></span></div><div class="arc-board-frame"><div id="arcBoard" class="arc-board" style="--cols:<?=$game['cols']?>;--rows:<?=$game['rows']?>;grid-template-columns:repeat(<?=$game['cols']?>,1fr);grid-template-rows:repeat(<?=$game['rows']?>,1fr)"></div><div id="arcOverlay" class="arc-overlay"></div></div><div id="arcMessage" class="arc-message">УДАЧИ!</div><div id="featureBox"></div>
  <div class="arc-controls"><div class="arc-wallet"><span>Баланс</span><strong id="walletValue"><?=e(money_rub((int)$user['balance_kopecks']))?></strong></div><div class="arc-bet"><button id="betMinus">−</button><div><span>Ставка</span><strong id="betValue">100 ₽</strong></div><button id="betPlus">+</button></div><button id="spinBtn" class="arc-spin"><span>↻</span><small>SPIN</small></button><div class="arc-actions"><button id="autoBtn" class="arc-action">АВТО ×20</button><button id="turboBtn" class="arc-action">⚡ ТУРБО</button><button id="soundBtn" class="arc-action">🔊 ЗВУК</button></div></div></div></section>
  <aside class="arc-side right"><h3 style="margin-top:3px">Другие слоты</h3><div class="arc-game-list"><?php foreach($all as $slug=>$g): $href=$slug==='sweet-cascade'?'game.php':$g['route']; ?><a class="arc-game-link <?=$slug===$key?'current':''?>" href="<?=e($href)?>"><i style="--g:<?=e($g['accent'])?>;background:<?=e($g['accent'])?>"><?=e($g['icon'])?></i><div><strong><?=e($g['title'])?></strong><small><?=e($g['subtitle'])?></small></div></a><?php endforeach; ?></div><a class="arc-mini-link" href="mini.php?game=plinko">● Плинко</a><a class="arc-mini-link" href="mini.php?game=mines">◆ Мины</a><a class="arc-mini-link" href="mini.php?game=wheel">◉ Колесо</a><p class="arc-rules">Все суммы виртуальные. Сервер рассчитывает результат до анимации. Персонального изменения шансов нет.</p></aside>
</main>
<script>window.ARCADE_BOOT=<?=json_encode($boot,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script><script src="<?=asset_url('arcade-symbols.js')?>"></script><script src="<?=asset_url('arcade-game.js')?>"></script>
</body></html>
