<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
require __DIR__.'/app/views.php';
require __DIR__.'/app/game_catalog.php';
require __DIR__.'/app/mini_catalog.php';
$user=require_login();$id=max(1,(int)($_GET['id']??0));$q=db()->prepare('SELECT r.*,u.username FROM game_rounds r JOIN users u ON u.id=r.user_id WHERE r.id=? LIMIT 1');$q->execute([$id]);$round=$q->fetch();if(!$round||((int)$round['user_id']!==(int)$user['id']&&!is_admin($user))){http_response_code(404);exit('Раунд не найден.');}
$games=game_catalog();$minis=mini_catalog();$key=(string)$round['game_key'];if(str_starts_with($key,'mini-')){$slug=substr($key,5);$meta=$minis[$slug]??null;$title=$meta['title']??$key;$icon=$meta['icon']??'•';}else{$meta=$games[$key]??null;$title=$meta['title']??$key;$icon=$meta['icon']??'•';}
$modeLabels=['normal'=>'Обычный','free'=>'Фриспин','buy_bonus'=>'Bonus Buy','buy_super'=>'Super Buy','active'=>'Активная','lost'=>'Проигрыш','cashed'=>'Забрано'];$mode=$modeLabels[$round['mode']]??$round['mode'];$receipt=substr(hash('sha256',$round['id'].'|'.$round['game_key'].'|'.$round['balance_before_kopecks'].'|'.$round['balance_after_kopecks'].'|'.$round['win_kopecks']),0,20);$result=json_decode((string)($round['result_json']??''),true);if(!is_array($result))$result=[];
$w=db()->prepare('SELECT type,amount_kopecks,balance_after_kopecks,metadata_json,created_at FROM wallet_transactions WHERE user_id=? AND reference=? ORDER BY id');$w->execute([(int)$round['user_id'],'round:'.$id]);$wallet=$w->fetchAll();
site_head('Раунд #'.$id.' — CandyClub');echo '<body class="cc-site">';site_nav($user);
?>
<main class="cc-container cc-account"><div class="cc-section-head"><div><h1 style="margin:0"><?=e($icon.' '.$title)?> • #<?=$id?></h1><p><?=e($mode)?> • <?=e(date('d.m.Y H:i:s',strtotime((string)$round['created_at'])))?><?php if(is_admin($user)&&(int)$round['user_id']!==(int)$user['id']): ?> • игрок <?=e($round['username'])?><?php endif; ?></p></div><a class="cc-btn" href="<?=is_admin($user)?'admin.php':'history.php'?>">← Назад</a></div>
<div class="cc-round-summary"><div><span>Ставка</span><strong><?=e(money_rub((int)$round['bet_kopecks']))?></strong></div><div><span>Стоимость раунда</span><strong><?=e(money_rub((int)$round['cost_kopecks']))?></strong></div><div><span>Выигрыш</span><strong class="<?=$round['win_kopecks']>0?'cc-plus':''?>"><?=e(money_rub((int)$round['win_kopecks']))?></strong></div><div><span>Баланс до</span><strong><?=e(money_rub((int)$round['balance_before_kopecks']))?></strong></div><div><span>Баланс после</span><strong><?=e(money_rub((int)$round['balance_after_kopecks']))?></strong></div><div><span>Квитанция</span><strong><code><?=e($receipt)?></code></strong></div></div>
<section class="cc-history" style="margin-top:16px"><div class="cc-section-head"><div><h2>Движения виртуального кошелька</h2><p>Операции, связанные именно с этим серверным раундом.</p></div></div><div style="overflow:auto"><table class="cc-table"><thead><tr><th>Тип</th><th>Изменение</th><th>Баланс после</th><th>Время</th></tr></thead><tbody><?php if(!$wallet): ?><tr><td colspan="4">Связанных операций нет.</td></tr><?php else: foreach($wallet as $row): ?><tr><td><?=e((string)$row['type'])?></td><td class="<?=$row['amount_kopecks']>=0?'cc-plus':'cc-minus'?>"><?=$row['amount_kopecks']>=0?'+':''?><?=e(money_rub((int)$row['amount_kopecks']))?></td><td><?=e(money_rub((int)$row['balance_after_kopecks']))?></td><td><?=e(date('d.m.Y H:i:s',strtotime((string)$row['created_at'])))?></td></tr><?php endforeach; endif; ?></tbody></table></div></section>
<details class="cc-round-tech"><summary>Технические данные результата</summary><p>Это диагностическая запись сервера, а не доказательство provably-fair или сертификат RNG.</p><pre><?=e(json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT)?:'{}')?></pre></details>
</main><?php site_footer(); ?>
