(function(){
'use strict';
var B=window.CC_RUNTIME||{};
function offline(show){var old=document.querySelector('.cc-offline');if(show&&!old){var e=document.createElement('div');e.className='cc-offline';e.textContent='Нет соединения. Новые игровые действия временно недоступны.';document.body.appendChild(e)}else if(!show&&old)old.remove()}
window.addEventListener('offline',function(){offline(true)});window.addEventListener('online',function(){offline(false)});if(!navigator.onLine)offline(true);
if(!B.loggedIn||!B.controls)return;var c=B.controls||{},rem=Number(c.session_reminder_minutes||0),pause=Number(c.pause_until||0),now=Math.floor(Date.now()/1000);
function modal(){if(document.querySelector('.cc-reality'))return;var start=Number(localStorage.getItem('ccSessionStarted')||0);if(!start){start=Date.now();localStorage.setItem('ccSessionStarted',String(start))}var mins=Math.max(1,Math.floor((Date.now()-start)/60000)),wrap=document.createElement('div');wrap.className='cc-reality';wrap.innerHTML='<div class="cc-reality-card"><span class="cc-reality-icon">◷</span><h3>Напоминание о сессии</h3><p>Эта игровая сессия длится примерно <strong>'+mins+' мин.</strong> Можно продолжить или перейти к настройкам лимитов.</p><div><button type="button" class="cc-btn cc-btn-primary" data-continue>Продолжить</button><a class="cc-btn" href="club.php#playControls">Контроль игры</a></div></div>';document.body.appendChild(wrap);wrap.querySelector('[data-continue]').addEventListener('click',function(){localStorage.setItem('ccLastReminder',String(Date.now()));wrap.remove()})}
try{if(!localStorage.getItem('ccSessionStarted'))localStorage.setItem('ccSessionStarted',String(Date.now()));}catch(e){}
if(rem>0)setInterval(function(){try{var last=Number(localStorage.getItem('ccLastReminder')||localStorage.getItem('ccSessionStarted')||Date.now());if(Date.now()-last>=rem*60000)modal()}catch(e){}},30000);
if(pause>now&&!document.querySelector('.cc-pause-banner')){var b=document.createElement('div');b.className='cc-pause-banner',d=new Date(pause*1000);b.innerHTML='<span>Игровая пауза активна до '+d.toLocaleString('ru-RU')+'.</span><a href="club.php#playControls">Подробнее</a>';document.body.appendChild(b)}
})();
