(function(){
'use strict';
var B=window.SWEET_BOOT||{},board=document.getElementById('arcBoard'),overlay=document.getElementById('arcOverlay'),msg=document.getElementById('arcMessage'),frame=document.querySelector('.arc-board-frame');var bets=[10,20,50,100,200,500,1000,2000],betIndex=3,busy=false,auto=0,turbo=false,soundOn=true,balance=Number(B.balance||0),free=Number(B.freeSpins||0),storm=Number(B.stormCharge||0),mults=B.multiplierMap||Array(49).fill(0),last=0,audio=null;var keys=Object.keys(B.symbols||{});
function q(s){return document.querySelector(s)}function rub(v){return new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:v%1?2:0}).format(v)}function bet(){return bets[betIndex]}function delay(ms){return new Promise(function(r){setTimeout(r,turbo?Math.max(30,ms*.28):ms)})}
function tone(kind,n){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();var now=audio.currentTime;function hit(f,t,d,g){var o=audio.createOscillator(),a=audio.createGain();o.type='triangle';o.frequency.value=f;a.gain.setValueAtTime(.001,now+t);a.gain.linearRampToValueAtTime(g||.03,now+t+.01);a.gain.exponentialRampToValueAtTime(.001,now+t+(d||.13));o.connect(a).connect(audio.destination);o.start(now+t);o.stop(now+t+(d||.13)+.03)}if(kind==='roll'){hit(260,0,.06,.014);hit(390,.04,.07,.012)}if(kind==='land')hit(430,0,.07,.02);if(kind==='win'){hit(480,0,.12,.03);hit(690,.08,.15,.035);hit(890,.16,.18,.04)}if(kind==='bonus'){for(var i=0;i<5;i++)hit(430+i*90,i*.07,.2,.035)}if(kind==='mult'){hit(720,0,.14,.035);hit(980,.08,.2,.035)}if(kind==='error')hit(110,0,.25,.04)}catch(e){}}
function update(){q('#walletValue').textContent=rub(balance);var bs=document.querySelectorAll('[data-balance]');for(var i=0;i<bs.length;i++)bs[i].textContent=rub(balance);q('#betValue').textContent=rub(bet());q('#freeValue').textContent=free;q('#lastWin').textContent=rub(last);q('#modeBadge').textContent=free>0?'ФРИСПИНЫ':'ОСНОВНАЯ';q('#stormBar').style.width=Math.max(0,Math.min(100,storm))+'%';q('#autoBtn').textContent=auto>0?'СТОП • '+auto:'АВТО ×20';q('#autoBtn').classList.toggle('active',auto>0);q('#turboBtn').classList.toggle('active',turbo);q('#soundBtn').textContent=soundOn?'🔊 ЗВУК':'🔇 ЗВУК';q('#buyPrice').textContent=rub(bet()*Number(B.buyBonus||80));q('#superBuyPrice').textContent=rub(bet()*Number(B.buySuper||250));q('#buyBtn').disabled=busy||free>0;q('#superBuyBtn').disabled=busy||free>0}
function markup(sym){var svg=window.ArcadeSymbols?window.ArcadeSymbols.render('sweet-cascade',sym):'';return '<span class="sym" title="'+((B.symbols[sym]&&B.symbols[sym].name)||sym)+'">'+svg+'</span>'}
function render(grid,map,changed){map=map||Array(49).fill(0);changed=changed||[];board.innerHTML='';for(var i=0;i<49;i++){var r=Math.floor(i/7),c=i%7,s=grid[i]||keys[0],el=document.createElement('div');el.className='arc-cell';el.style.gridColumn=String(c+1);el.style.gridRow=String(r+1);el.setAttribute('data-index',String(i));el.setAttribute('data-sym',s);el.innerHTML=markup(s);if(Number(map[i]||0)>0){var b=document.createElement('b');b.className='sweet-mult'+(changed.indexOf(i)>=0?' up':'');b.textContent='×'+map[i];el.appendChild(b)}board.appendChild(el)}}
function randomSym(){return keys[Math.floor(Math.random()*keys.length)]}
async function roll(target){if(!board.children.length)render(Array(49).fill(0).map(randomSym),mults);var cells=Array.prototype.slice.call(board.children);for(var i=0;i<cells.length;i++)cells[i].classList.add('roll');q('#statusLeft').textContent='ПРОКРУТ';for(var k=0;k<7;k++){for(var z=0;z<cells.length;z++)cells[z].querySelector('.sym').innerHTML=window.ArcadeSymbols.render('sweet-cascade',randomSym());tone('roll');await delay(75)}for(var c=0;c<7;c++){for(var rr=0;rr<7;rr++){var idx=rr*7+c;cells[idx].innerHTML=markup(target[idx]);cells[idx].classList.remove('roll');cells[idx].classList.add('land')}tone('land');await delay(105)}render(target,mults);await delay(150)}
function markClusters(clusters){for(var c=0;c<clusters.length;c++)for(var j=0;j<clusters[c].cells.length;j++){var e=board.children[clusters[c].cells[j]];if(e)e.classList.add('win')}}
async function winPop(v,label){var e=document.createElement('div');e.className='arc-win-pop';e.innerHTML=rub(v)+'<small>'+label+'</small>';overlay.innerHTML='';overlay.appendChild(e);tone('win');await delay(v>=bet()*10?780:520);overlay.innerHTML=''}
async function bigWin(v){if(v<bet()*10)return;var tier=v>=bet()*50?'EPIC WIN':(v>=bet()*25?'MEGA WIN':'BIG WIN');var e=document.createElement('div');e.className='arc-bigwin';e.innerHTML='<strong>'+tier+'</strong><span>'+rub(v)+'</span><small>'+Number(v/bet()).toFixed(1)+'× СТАВКИ</small>';overlay.innerHTML='';overlay.appendChild(e);tone('bonus');await delay(v>=bet()*50?1900:1300);overlay.innerHTML=''}
async function featureIntro(text,sub){var e=document.createElement('div');e.className='arc-feature-intro';e.innerHTML='<div><strong>'+text+'</strong><span>'+sub+'</span></div>';frame.appendChild(e);tone('bonus');await delay(1100);e.remove()}
async function spin(mode){mode=mode||'normal';if(busy)return;var cost=mode==='buy_bonus'?bet()*80:(mode==='buy_super'?bet()*250:(free>0?0:bet()));if(balance<cost){msg.textContent='НЕДОСТАТОЧНО ВИРТУАЛЬНЫХ СРЕДСТВ';tone('error');return}busy=true;q('#spinBtn').classList.add('busy');q('#betMinus').disabled=q('#betPlus').disabled=true;update();try{var res=await fetch('api/game/sweet-cascade/spin.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-Token':B.csrf},body:JSON.stringify({bet:bet(),mode:mode})});var d=await res.json().catch(function(){return{ok:false,error:'Некорректный ответ сервера.'}});if(!res.ok||!d.ok)throw new Error(d.error||'Ошибка игры.');balance=Number(d.balance_before)-Number(d.cost);if(d.is_free_spin)free=Math.max(0,free-1);last=0;mults=d.initial_multipliers||mults;update();if(d.storm_active)await featureIntro('СЛАДКИЙ ШТОРМ','УСИЛЕННЫЕ КЛЕТКИ АКТИВНЫ');await roll(d.initial_grid);var cumulative=0;for(var si=0;si<d.steps.length;si++){var s=d.steps[si];markClusters(s.clusters||[]);cumulative+=Number(s.win||0);last=cumulative;q('#statusLeft').textContent='КАСКАД '+s.cascade;msg.textContent='КАСКАД '+s.cascade+' • +'+rub(Number(s.win||0));update();await winPop(Number(s.win||0),'КАСКАД ×'+Number(s.combo||1).toFixed(2));var changed=[];for(var ci=0;ci<(s.multiplier_changes||[]).length;ci++)changed.push(s.multiplier_changes[ci].pos);mults=s.multipliers_after||mults;render(s.grid_after,mults,changed);if(changed.length){tone('mult');msg.textContent='МНОЖИТЕЛИ КЛЕТОК УСИЛЕНЫ';await delay(420)}else await delay(300)}if(Number(d.free_spins_awarded||0)>0)await featureIntro('+'+d.free_spins_awarded+' ФРИСПИНОВ','МНОЖИТЕЛИ СОХРАНЯЮТСЯ');balance=Number(d.balance_after);free=Number(d.free_spins||0);storm=Number(d.storm_charge||0);last=Number(d.total_win||0);mults=d.final_multipliers||mults;render(d.final_grid,mults);q('#statusLeft').textContent='ГОТОВО';q('#statusRight').textContent=free>0?'ФРИСПИНЫ • МНОЖИТЕЛИ СОХРАНЕНЫ':'КЛАСТЕРЫ 6+ • КАСКАДЫ';msg.textContent=last>0?'ИТОГ '+rub(last):(free>0?'СЛЕДУЮЩИЙ ФРИСПИН':'ЕЩЁ РАЗ!');update();await bigWin(last);busy=false;q('#spinBtn').classList.remove('busy');q('#betMinus').disabled=q('#betPlus').disabled=false;update();if(free>0){await delay(950);if(!busy)spin('normal');return}if(auto>0&&mode==='normal'){auto--;update();if(auto>0){await delay(850);spin('normal')}}}catch(e){busy=false;auto=0;q('#spinBtn').classList.remove('busy');q('#betMinus').disabled=q('#betPlus').disabled=false;msg.textContent=e.message||'ОШИБКА';tone('error');update()}}
q('#betMinus').onclick=function(){if(!busy&&free<=0){betIndex=Math.max(0,betIndex-1);update()}};q('#betPlus').onclick=function(){if(!busy&&free<=0){betIndex=Math.min(bets.length-1,betIndex+1);update()}};q('#spinBtn').onclick=function(){spin('normal')};q('#buyBtn').onclick=function(){var cost=bet()*80;if(!busy&&free<=0&&confirm('Купить фриспины за '+rub(cost)+' виртуального баланса?'))spin('buy_bonus')};q('#superBuyBtn').onclick=function(){var cost=bet()*250;if(!busy&&free<=0&&confirm('Купить супер-бонус за '+rub(cost)+' виртуального баланса?'))spin('buy_super')};q('#autoBtn').onclick=function(){if(auto){auto=0;update();return}auto=20;update();spin('normal')};q('#turboBtn').onclick=function(){turbo=!turbo;update()};q('#soundBtn').onclick=function(){soundOn=!soundOn;update();if(soundOn)tone('land')};document.addEventListener('keydown',function(e){if(e.code==='Space'&&!e.repeat){e.preventDefault();spin('normal')}});render(Array(49).fill(0).map(randomSym),mults);update();
})();
