<?php
declare(strict_types=1);
require_once __DIR__.'/mini_games.php';

function mini_dice_options(): array {return [10=>9.60,20=>4.80,35=>2.74,50=>1.92,70=>1.37];}
function mini_dice(PDO $pdo,int $userId,int $betRub,int $chance): array {
    $options=mini_dice_options();if(!isset($options[$chance]))throw new RuntimeException('Недопустимый уровень риска.');
    $rollInt=random_int(0,9999);$roll=$rollInt/100;$success=$rollInt<$chance*100;$mult=$success?(float)$options[$chance]:0.0;
    return mini_direct_round($pdo,$userId,'dice',$betRub,$mult,['chance'=>$chance,'roll'=>$roll,'success'=>$success,'target'=>'< '.$chance.'.00']);
}

function mini_tower_multiplier(int $level): float {
    if($level<=0)return 1.0;$level=min(8,$level);return round(.96/pow(2/3,$level),2);
}
function mini_tower_state_ensure(PDO $pdo,int $userId): void {$pdo->prepare("INSERT IGNORE INTO user_game_states(user_id,game_key,free_spins,storm_charge,multiplier_map_json) VALUES(?,'mini-tower',0,0,'{}')")->execute([$userId]);}
function mini_tower_store(PDO $pdo,int $userId,array $state): void {$pdo->prepare("INSERT INTO user_game_states(user_id,game_key,free_spins,storm_charge,multiplier_map_json) VALUES(?,'mini-tower',0,0,?) ON DUPLICATE KEY UPDATE multiplier_map_json=VALUES(multiplier_map_json),updated_at=CURRENT_TIMESTAMP")->execute([$userId,json_encode($state,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}
function mini_tower_clear(PDO $pdo,int $userId): void {$pdo->prepare("INSERT INTO user_game_states(user_id,game_key,free_spins,storm_charge,multiplier_map_json) VALUES(?,'mini-tower',0,0,'{}') ON DUPLICATE KEY UPDATE multiplier_map_json='{}',updated_at=CURRENT_TIMESTAMP")->execute([$userId]);}
function mini_tower_get(int $userId): ?array {if(!function_exists('db'))return null;$q=db()->prepare("SELECT multiplier_map_json FROM user_game_states WHERE user_id=? AND game_key='mini-tower' LIMIT 1");$q->execute([$userId]);$raw=$q->fetchColumn();if(!$raw)return null;$s=json_decode((string)$raw,true);if(!is_array($s)||empty($s['round'])||!isset($s['level'],$s['betK'],$s['history']))return null;return $s;}
function mini_tower_start(PDO $pdo,int $userId,int $betRub): array {
    cc_play_guard($userId,$betRub,true);$betK=mini_validate_bet($betRub);$pdo->beginTransaction();
    try{mini_tower_state_ensure($pdo,$userId);$sq=$pdo->prepare("SELECT multiplier_map_json FROM user_game_states WHERE user_id=? AND game_key='mini-tower' FOR UPDATE");$sq->execute([$userId]);$raw=$sq->fetchColumn();$existing=$raw?json_decode((string)$raw,true):[];if(is_array($existing)&&!empty($existing['round']))throw new RuntimeException('Сначала завершите активную Башню импульса.');$q=$pdo->prepare('SELECT balance_kopecks FROM users WHERE id=? FOR UPDATE');$q->execute([$userId]);$u=$q->fetch();if(!$u)throw new RuntimeException('Аккаунт не найден.');$before=(int)$u['balance_kopecks'];if($before<$betK)throw new RuntimeException('Недостаточно виртуальных средств.');$after=$before-$betK;$pdo->prepare('UPDATE users SET balance_kopecks=? WHERE id=?')->execute([$after,$userId]);$pdo->prepare('INSERT INTO game_rounds(user_id,game_key,mode,bet_kopecks,cost_kopecks,win_kopecks,balance_before_kopecks,balance_after_kopecks,result_json) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$userId,'mini-tower','active',$betK,$betK,0,$before,$after,json_encode(['level'=>0,'history'=>[]],JSON_UNESCAPED_UNICODE)]);$round=(int)$pdo->lastInsertId();wallet_entry($pdo,$userId,'game_bet',-$betK,$after,'round:'.$round,['game'=>'mini-tower']);$state=['round'=>$round,'level'=>0,'betK'=>$betK,'history'=>[],'started'=>time()];mini_tower_store($pdo,$userId,$state);$pdo->commit();return ['ok'=>true,'game'=>'tower','state'=>'active','round_id'=>$round,'bet'=>$betRub,'level'=>0,'history'=>[],'multiplier'=>1.0,'potential_win'=>0,'balance_after'=>$after/100];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function mini_tower_reveal(PDO $pdo,int $userId,int $portal): array {
    cc_play_guard($userId,null,false);if($portal<0||$portal>2)throw new RuntimeException('Некорректный портал.');$pdo->beginTransaction();
    try{mini_tower_state_ensure($pdo,$userId);$sq=$pdo->prepare("SELECT multiplier_map_json FROM user_game_states WHERE user_id=? AND game_key='mini-tower' FOR UPDATE");$sq->execute([$userId]);$raw=$sq->fetchColumn();$s=$raw?json_decode((string)$raw,true):null;if(!is_array($s)||empty($s['round']))throw new RuntimeException('Активная Башня не найдена.');$level=(int)($s['level']??0);if($level>=8)throw new RuntimeException('Башня уже пройдена.');$trap=random_int(0,2);$safe=$portal!==$trap;$s['history'][]=['floor'=>$level+1,'choice'=>$portal,'trap'=>$trap,'safe'=>$safe];if(!$safe){$pdo->prepare('UPDATE game_rounds SET mode=?,result_json=? WHERE id=? AND user_id=?')->execute(['lost',json_encode(['level'=>$level,'history'=>$s['history']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),(int)$s['round'],$userId]);mini_tower_clear($pdo,$userId);$pdo->commit();return ['ok'=>true,'game'=>'tower','state'=>'lost','round_id'=>(int)$s['round'],'level'=>$level,'choice'=>$portal,'trap'=>$trap,'history'=>$s['history'],'multiplier'=>0,'win'=>0];}$level++;$s['level']=$level;$mult=mini_tower_multiplier($level);$potential=round((int)$s['betK']*$mult/100,2);if($level>=8){$q=$pdo->prepare('SELECT balance_kopecks FROM users WHERE id=? FOR UPDATE');$q->execute([$userId]);$u=$q->fetch();if(!$u)throw new RuntimeException('Аккаунт не найден.');$winK=(int)round((int)$s['betK']*$mult);$before=(int)$u['balance_kopecks'];$after=$before+$winK;$pdo->prepare('UPDATE users SET balance_kopecks=? WHERE id=?')->execute([$after,$userId]);$pdo->prepare('UPDATE game_rounds SET mode=?,win_kopecks=?,balance_after_kopecks=?,result_json=? WHERE id=? AND user_id=?')->execute(['cashed',$winK,$after,json_encode(['level'=>$level,'multiplier'=>$mult,'history'=>$s['history'],'auto'=>true],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),(int)$s['round'],$userId]);wallet_entry($pdo,$userId,'game_win',$winK,$after,'round:'.$s['round'],['game'=>'mini-tower','multiplier'=>$mult]);mini_tower_clear($pdo,$userId);$pdo->commit();return ['ok'=>true,'game'=>'tower','state'=>'cashed','round_id'=>(int)$s['round'],'level'=>$level,'choice'=>$portal,'trap'=>$trap,'history'=>$s['history'],'multiplier'=>$mult,'win'=>$winK/100,'balance_after'=>$after/100,'auto'=>true];}mini_tower_store($pdo,$userId,$s);$pdo->commit();return ['ok'=>true,'game'=>'tower','state'=>'active','round_id'=>(int)$s['round'],'level'=>$level,'choice'=>$portal,'trap'=>$trap,'history'=>$s['history'],'multiplier'=>$mult,'potential_win'=>$potential];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function mini_tower_cashout(PDO $pdo,int $userId): array {
    $pdo->beginTransaction();try{mini_tower_state_ensure($pdo,$userId);$sq=$pdo->prepare("SELECT multiplier_map_json FROM user_game_states WHERE user_id=? AND game_key='mini-tower' FOR UPDATE");$sq->execute([$userId]);$raw=$sq->fetchColumn();$s=$raw?json_decode((string)$raw,true):null;if(!is_array($s)||empty($s['round']))throw new RuntimeException('Активная Башня не найдена.');$level=(int)($s['level']??0);if($level<=0)throw new RuntimeException('Сначала пройдите хотя бы один этаж.');$mult=mini_tower_multiplier($level);$winK=(int)round((int)$s['betK']*$mult);$q=$pdo->prepare('SELECT balance_kopecks FROM users WHERE id=? FOR UPDATE');$q->execute([$userId]);$u=$q->fetch();if(!$u)throw new RuntimeException('Аккаунт не найден.');$before=(int)$u['balance_kopecks'];$after=$before+$winK;$pdo->prepare('UPDATE users SET balance_kopecks=? WHERE id=?')->execute([$after,$userId]);$pdo->prepare('UPDATE game_rounds SET mode=?,win_kopecks=?,balance_after_kopecks=?,result_json=? WHERE id=? AND user_id=?')->execute(['cashed',$winK,$after,json_encode(['level'=>$level,'multiplier'=>$mult,'history'=>$s['history'],'auto'=>false],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),(int)$s['round'],$userId]);wallet_entry($pdo,$userId,'game_win',$winK,$after,'round:'.$s['round'],['game'=>'mini-tower','multiplier'=>$mult]);mini_tower_clear($pdo,$userId);$pdo->commit();return ['ok'=>true,'game'=>'tower','state'=>'cashed','round_id'=>(int)$s['round'],'level'=>$level,'history'=>$s['history'],'multiplier'=>$mult,'win'=>$winK/100,'balance_after'=>$after/100];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}

function daily_reward_schedule(): array {return [7500,10000,12500,15000,20000,25000,40000];}
function daily_reward_streak_info(PDO $pdo,int $userId): array {
    $q=$pdo->prepare("SELECT DATE(created_at) day FROM wallet_transactions WHERE user_id=? AND type='daily_bonus' GROUP BY DATE(created_at) ORDER BY day DESC LIMIT 370");$q->execute([$userId]);$days=array_values(array_map('strval',$q->fetchAll(PDO::FETCH_COLUMN)));$today=(string)$pdo->query('SELECT CURDATE()')->fetchColumn();$yesterday=(string)$pdo->query("SELECT DATE_SUB(CURDATE(),INTERVAL 1 DAY)")->fetchColumn();$claimedToday=in_array($today,$days,true);$anchor=$claimedToday?$today:$yesterday;$set=array_flip($days);$streak=0;$cursor=$anchor;while(isset($set[$cursor])&&$streak<365){$streak++;$q2=$pdo->prepare('SELECT DATE_SUB(?,INTERVAL 1 DAY)');$q2->execute([$cursor]);$cursor=(string)$q2->fetchColumn();}$continues=$claimedToday||isset($set[$yesterday]);$nextDay=$continues?($streak%7)+1:1;$schedule=daily_reward_schedule();return ['available'=>!$claimedToday,'last'=>$days[0]??null,'streak'=>$streak,'cycle_day'=>$streak>0?(($streak-1)%7)+1:0,'next_day'=>$nextDay,'next_bonus'=>$schedule[$nextDay-1]/100];
}
function daily_reward_status_v2(PDO $pdo,int $userId): array {return daily_reward_streak_info($pdo,$userId);}
function daily_reward_claim_v2(PDO $pdo,int $userId): array {
    $pdo->beginTransaction();try{$q=$pdo->prepare('SELECT balance_kopecks FROM users WHERE id=? FOR UPDATE');$q->execute([$userId]);$u=$q->fetch();if(!$u)throw new RuntimeException('Аккаунт не найден.');$dup=$pdo->prepare("SELECT id FROM wallet_transactions WHERE user_id=? AND type='daily_bonus' AND created_at>=CURDATE() LIMIT 1 FOR UPDATE");$dup->execute([$userId]);if($dup->fetch())throw new RuntimeException('Ежедневный подарок уже получен сегодня.');$info=daily_reward_streak_info($pdo,$userId);$day=max(1,min(7,(int)$info['next_day']));$schedule=daily_reward_schedule();$bonus=$schedule[$day-1];$before=(int)$u['balance_kopecks'];$after=$before+$bonus;$pdo->prepare('UPDATE users SET balance_kopecks=? WHERE id=?')->execute([$after,$userId]);wallet_entry($pdo,$userId,'daily_bonus',$bonus,$after,'daily:'.cc_db_today(),['source'=>'daily_streak','day'=>$day]);$pdo->commit();return ['ok'=>true,'bonus'=>$bonus/100,'balance_after'=>$after/100,'streak'=>(int)$info['streak']+1,'day'=>$day,'cycle_complete'=>$day===7];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
