<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
require dirname(__DIR__).'/app/arcade_v2.php';
require dirname(__DIR__).'/app/sweet_cascade.php';
require dirname(__DIR__).'/app/mini_games.php';
require dirname(__DIR__).'/app/mini_expansion.php';
require dirname(__DIR__).'/app/privacy.php';

function smoke_assert(bool $ok,string $message): void {if(!$ok)throw new RuntimeException($message);}
$pdo=db();$name='ci_'.bin2hex(random_bytes(4));$email=$name.'@example.test';$uid=0;
try{
    $start=50000000;$q=$pdo->prepare('INSERT INTO users(username,email,password_hash,balance_kopecks) VALUES(?,?,?,?)');$q->execute([$name,$email,password_hash('Integration123',PASSWORD_DEFAULT),$start]);$uid=(int)$pdo->lastInsertId();wallet_entry($pdo,$uid,'welcome_bonus',$start,$start,'ci-signup');echo "user {$uid} created\n";

    foreach(['fruit-fiesta','forge-tempest','lunar-beasts','clockwork-shift'] as $game){$slot=arcade_game_spin_hv($pdo,$uid,$game,100,'normal');smoke_assert(!empty($slot['round_id'])&&isset($slot['balance_after'],$slot['initial_grid']),$game.' failed');echo "slot {$game} OK #{$slot['round_id']}\n";}
    $buy=arcade_game_spin_hv($pdo,$uid,'forge-tempest',20,'buy_bonus');smoke_assert(($buy['mode']??'')==='buy_bonus'&&($buy['free_spins']??0)>0,'expansion bonus buy failed');echo "forge bonus buy OK\n";$guard=0;while(($buy['free_spins']??0)>0&&$guard++<80){$buy=arcade_game_spin_hv($pdo,$uid,'forge-tempest',20,'normal');}smoke_assert($guard<80,'forge free-spin chain exceeded smoke bound');echo "forge free spins settle OK\n";
    $sweet=sweet_cascade_spin($pdo,$uid,100,'normal');smoke_assert(!empty($sweet['round_id'])&&isset($sweet['final_grid']),'sweet failed');echo "sweet OK #{$sweet['round_id']}\n";

    $plinko=mini_plinko($pdo,$uid,100);smoke_assert(count($plinko['path'])===12&&isset($plinko['bin']),'plinko failed');$wheel=mini_wheel($pdo,$uid,100);smoke_assert(isset($wheel['segment'],$wheel['multiplier']),'wheel failed');$crash=mini_crash($pdo,$uid,100,2.0);smoke_assert(isset($crash['crash_point'],$crash['success'])&&$crash['crash_point']>=1,'crash failed');$dice=mini_dice($pdo,$uid,100,35);smoke_assert(isset($dice['roll'],$dice['success'])&&$dice['roll']>=0&&$dice['roll']<100,'dice failed');echo "instant games OK\n";

    $mines=mini_mines_start($pdo,$uid,100,5);smoke_assert(($mines['state']??'')==='active','mines start failed');$state=mini_mines_get($uid);smoke_assert(is_array($state)&&count($state['board'])===25,'mines state failed');$sq=$pdo->prepare('SELECT game_key,free_spins,storm_charge,multiplier_map_json,updated_at FROM user_game_states WHERE user_id=? AND game_key=?');$sq->execute([$uid,'mini-mines']);$exportState=cc_sanitize_game_state_for_export($sq->fetch()?:[]);$safeDecoded=json_decode((string)($exportState['multiplier_map_json']??''),true);smoke_assert(is_array($safeDecoded)&&!array_key_exists('board',$safeDecoded),'active Mines board leaked through export sanitizer');smoke_assert(($safeDecoded['round']??null)===$state['round'],'sanitized Mines export lost round id');$safe=null;foreach($state['board'] as $i=>$mine){if(!$mine){$safe=(int)$i;break;}}smoke_assert($safe!==null,'no safe cell');$reveal=mini_mines_reveal($pdo,$uid,$safe);if($reveal['state']==='active'){$cash=mini_mines_cashout($pdo,$uid);smoke_assert(($cash['state']??'')==='cashed'&&$cash['win']>0,'mines cashout failed');}echo "mines OK\n";

    $towerSafe=false;for($attempt=0;$attempt<12&&!$towerSafe;$attempt++){$startTower=mini_tower_start($pdo,$uid,50);smoke_assert(($startTower['state']??'')==='active','tower start failed');$saved=mini_tower_get($uid);smoke_assert(is_array($saved)&&($saved['level']??-1)===0,'tower persistence failed');$step=mini_tower_reveal($pdo,$uid,0);if(($step['state']??'')==='active'){$towerSafe=true;$saved=mini_tower_get($uid);smoke_assert(is_array($saved)&&($saved['level']??0)===1,'tower safe level not persisted');$sq=$pdo->prepare('SELECT game_key,free_spins,storm_charge,multiplier_map_json,updated_at FROM user_game_states WHERE user_id=? AND game_key=?');$sq->execute([$uid,'mini-tower']);$towerExport=cc_sanitize_game_state_for_export($sq->fetch()?:[]);$towerDecoded=json_decode((string)($towerExport['multiplier_map_json']??''),true);smoke_assert(is_array($towerDecoded)&&isset($towerDecoded['history'])&&!isset($towerDecoded['future_traps']),'tower export invalid');$cash=mini_tower_cashout($pdo,$uid);smoke_assert(($cash['state']??'')==='cashed'&&$cash['win']>0,'tower cashout failed');}}smoke_assert($towerSafe,'tower never produced a safe first floor during smoke attempts');echo "tower persistence/cashout OK\n";

    $daily=daily_reward_claim_v2($pdo,$uid);smoke_assert((float)$daily['bonus']===75.0&&$daily['day']===1,'daily streak day one failed');$status=daily_reward_status_v2($pdo,$uid);smoke_assert($status['available']===false&&$status['streak']>=1,'daily duplicate guard/streak failed');echo "daily streak OK\n";
    $favs=cc_toggle_favorite($uid,'forge-tempest');smoke_assert(in_array('forge-tempest',$favs,true),'favorite add failed');$favs=cc_toggle_favorite($uid,'forge-tempest');smoke_assert(!in_array('forge-tempest',$favs,true),'favorite remove failed');echo "favorites OK\n";
    $ctrl=cc_set_controls($uid,100,15,0);smoke_assert($ctrl['max_bet_rub']===100,'control save failed');$blocked=false;try{sweet_cascade_spin($pdo,$uid,200,'normal');}catch(RuntimeException $e){$blocked=str_contains($e->getMessage(),'личного лимита');}smoke_assert($blocked,'stake cap was not enforced');cc_set_controls($uid,0,60,0);echo "play controls OK\n";

    $integrity=$pdo->prepare('SELECT COUNT(*) FROM wallet_transactions WHERE user_id=?');$integrity->execute([$uid]);smoke_assert((int)$integrity->fetchColumn()>=15,'wallet journal unexpectedly short');$r=$pdo->prepare('SELECT COUNT(*) FROM game_rounds WHERE user_id=?');$r->execute([$uid]);smoke_assert((int)$r->fetchColumn()>=12,'round journal unexpectedly short');echo "journals OK\nINTEGRATION_SMOKE_OK\n";
}finally{if($uid>0){$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$uid]);echo "cleanup OK\n";}}
